/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/fleetengine.proto

package google.maps.fleetengine.v1;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maps.fleetengine.v1.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A full, human-readable address for this place.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
   * @return Whether the formattedAddress field is set.
   */
  boolean hasFormattedAddress();
  /**
   * <pre>
   * A full, human-readable address for this place.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
   * @return The formattedAddress.
   */
  google.maps.fleetengine.v1.FormattedAddress getFormattedAddress();
  /**
   * <pre>
   * A full, human-readable address for this place.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
   */
  google.maps.fleetengine.v1.FormattedAddressOrBuilder getFormattedAddressOrBuilder();
}
