/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/fleetengine.proto

package google.maps.fleetengine.v1;

/**
 * <pre>
 * Address of a place.
 * </pre>
 *
 * Protobuf type {@code maps.fleetengine.v1.Address}
 */
public final class Address extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:maps.fleetengine.v1.Address)
    AddressOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Address.newBuilder() to construct.
  private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Address() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Address();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Address(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            google.maps.fleetengine.v1.FormattedAddress.Builder subBuilder = null;
            if (formattedAddress_ != null) {
              subBuilder = formattedAddress_.toBuilder();
            }
            formattedAddress_ = input.readMessage(google.maps.fleetengine.v1.FormattedAddress.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(formattedAddress_);
              formattedAddress_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return google.maps.fleetengine.v1.FleetEngine.internal_static_maps_fleetengine_v1_Address_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return google.maps.fleetengine.v1.FleetEngine.internal_static_maps_fleetengine_v1_Address_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            google.maps.fleetengine.v1.Address.class, google.maps.fleetengine.v1.Address.Builder.class);
  }

  public static final int FORMATTED_ADDRESS_FIELD_NUMBER = 1;
  private google.maps.fleetengine.v1.FormattedAddress formattedAddress_;
  /**
   * <pre>
   * A full, human-readable address for this place.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
   * @return Whether the formattedAddress field is set.
   */
  @java.lang.Override
  public boolean hasFormattedAddress() {
    return formattedAddress_ != null;
  }
  /**
   * <pre>
   * A full, human-readable address for this place.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
   * @return The formattedAddress.
   */
  @java.lang.Override
  public google.maps.fleetengine.v1.FormattedAddress getFormattedAddress() {
    return formattedAddress_ == null ? google.maps.fleetengine.v1.FormattedAddress.getDefaultInstance() : formattedAddress_;
  }
  /**
   * <pre>
   * A full, human-readable address for this place.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
   */
  @java.lang.Override
  public google.maps.fleetengine.v1.FormattedAddressOrBuilder getFormattedAddressOrBuilder() {
    return getFormattedAddress();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (formattedAddress_ != null) {
      output.writeMessage(1, getFormattedAddress());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (formattedAddress_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getFormattedAddress());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof google.maps.fleetengine.v1.Address)) {
      return super.equals(obj);
    }
    google.maps.fleetengine.v1.Address other = (google.maps.fleetengine.v1.Address) obj;

    if (hasFormattedAddress() != other.hasFormattedAddress()) return false;
    if (hasFormattedAddress()) {
      if (!getFormattedAddress()
          .equals(other.getFormattedAddress())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFormattedAddress()) {
      hash = (37 * hash) + FORMATTED_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getFormattedAddress().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static google.maps.fleetengine.v1.Address parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.Address parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.Address parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.Address parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.Address parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.Address parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.Address parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.Address parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.Address parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.Address parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.Address parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.Address parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(google.maps.fleetengine.v1.Address prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Address of a place.
   * </pre>
   *
   * Protobuf type {@code maps.fleetengine.v1.Address}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:maps.fleetengine.v1.Address)
      google.maps.fleetengine.v1.AddressOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.maps.fleetengine.v1.FleetEngine.internal_static_maps_fleetengine_v1_Address_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.maps.fleetengine.v1.FleetEngine.internal_static_maps_fleetengine_v1_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.maps.fleetengine.v1.Address.class, google.maps.fleetengine.v1.Address.Builder.class);
    }

    // Construct using google.maps.fleetengine.v1.Address.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (formattedAddressBuilder_ == null) {
        formattedAddress_ = null;
      } else {
        formattedAddress_ = null;
        formattedAddressBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return google.maps.fleetengine.v1.FleetEngine.internal_static_maps_fleetengine_v1_Address_descriptor;
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.Address getDefaultInstanceForType() {
      return google.maps.fleetengine.v1.Address.getDefaultInstance();
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.Address build() {
      google.maps.fleetengine.v1.Address result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.Address buildPartial() {
      google.maps.fleetengine.v1.Address result = new google.maps.fleetengine.v1.Address(this);
      if (formattedAddressBuilder_ == null) {
        result.formattedAddress_ = formattedAddress_;
      } else {
        result.formattedAddress_ = formattedAddressBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof google.maps.fleetengine.v1.Address) {
        return mergeFrom((google.maps.fleetengine.v1.Address)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(google.maps.fleetengine.v1.Address other) {
      if (other == google.maps.fleetengine.v1.Address.getDefaultInstance()) return this;
      if (other.hasFormattedAddress()) {
        mergeFormattedAddress(other.getFormattedAddress());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      google.maps.fleetengine.v1.Address parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (google.maps.fleetengine.v1.Address) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private google.maps.fleetengine.v1.FormattedAddress formattedAddress_;
    private com.google.protobuf.SingleFieldBuilderV3<
        google.maps.fleetengine.v1.FormattedAddress, google.maps.fleetengine.v1.FormattedAddress.Builder, google.maps.fleetengine.v1.FormattedAddressOrBuilder> formattedAddressBuilder_;
    /**
     * <pre>
     * A full, human-readable address for this place.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
     * @return Whether the formattedAddress field is set.
     */
    public boolean hasFormattedAddress() {
      return formattedAddressBuilder_ != null || formattedAddress_ != null;
    }
    /**
     * <pre>
     * A full, human-readable address for this place.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
     * @return The formattedAddress.
     */
    public google.maps.fleetengine.v1.FormattedAddress getFormattedAddress() {
      if (formattedAddressBuilder_ == null) {
        return formattedAddress_ == null ? google.maps.fleetengine.v1.FormattedAddress.getDefaultInstance() : formattedAddress_;
      } else {
        return formattedAddressBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * A full, human-readable address for this place.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
     */
    public Builder setFormattedAddress(google.maps.fleetengine.v1.FormattedAddress value) {
      if (formattedAddressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        formattedAddress_ = value;
        onChanged();
      } else {
        formattedAddressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * A full, human-readable address for this place.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
     */
    public Builder setFormattedAddress(
        google.maps.fleetengine.v1.FormattedAddress.Builder builderForValue) {
      if (formattedAddressBuilder_ == null) {
        formattedAddress_ = builderForValue.build();
        onChanged();
      } else {
        formattedAddressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * A full, human-readable address for this place.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
     */
    public Builder mergeFormattedAddress(google.maps.fleetengine.v1.FormattedAddress value) {
      if (formattedAddressBuilder_ == null) {
        if (formattedAddress_ != null) {
          formattedAddress_ =
            google.maps.fleetengine.v1.FormattedAddress.newBuilder(formattedAddress_).mergeFrom(value).buildPartial();
        } else {
          formattedAddress_ = value;
        }
        onChanged();
      } else {
        formattedAddressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * A full, human-readable address for this place.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
     */
    public Builder clearFormattedAddress() {
      if (formattedAddressBuilder_ == null) {
        formattedAddress_ = null;
        onChanged();
      } else {
        formattedAddress_ = null;
        formattedAddressBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * A full, human-readable address for this place.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
     */
    public google.maps.fleetengine.v1.FormattedAddress.Builder getFormattedAddressBuilder() {
      
      onChanged();
      return getFormattedAddressFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * A full, human-readable address for this place.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
     */
    public google.maps.fleetengine.v1.FormattedAddressOrBuilder getFormattedAddressOrBuilder() {
      if (formattedAddressBuilder_ != null) {
        return formattedAddressBuilder_.getMessageOrBuilder();
      } else {
        return formattedAddress_ == null ?
            google.maps.fleetengine.v1.FormattedAddress.getDefaultInstance() : formattedAddress_;
      }
    }
    /**
     * <pre>
     * A full, human-readable address for this place.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        google.maps.fleetengine.v1.FormattedAddress, google.maps.fleetengine.v1.FormattedAddress.Builder, google.maps.fleetengine.v1.FormattedAddressOrBuilder> 
        getFormattedAddressFieldBuilder() {
      if (formattedAddressBuilder_ == null) {
        formattedAddressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            google.maps.fleetengine.v1.FormattedAddress, google.maps.fleetengine.v1.FormattedAddress.Builder, google.maps.fleetengine.v1.FormattedAddressOrBuilder>(
                getFormattedAddress(),
                getParentForChildren(),
                isClean());
        formattedAddress_ = null;
      }
      return formattedAddressBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:maps.fleetengine.v1.Address)
  }

  // @@protoc_insertion_point(class_scope:maps.fleetengine.v1.Address)
  private static final google.maps.fleetengine.v1.Address DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new google.maps.fleetengine.v1.Address();
  }

  public static google.maps.fleetengine.v1.Address getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Address>
      PARSER = new com.google.protobuf.AbstractParser<Address>() {
    @java.lang.Override
    public Address parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Address(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Address> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Address> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public google.maps.fleetengine.v1.Address getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

