/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/vehicles.proto

package google.maps.fleetengine.v1;

/**
 * <pre>
 * Information about the device's battery.
 * </pre>
 *
 * Protobuf type {@code maps.fleetengine.v1.BatteryInfo}
 */
public final class BatteryInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:maps.fleetengine.v1.BatteryInfo)
    BatteryInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BatteryInfo.newBuilder() to construct.
  private BatteryInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BatteryInfo() {
    batteryStatus_ = 0;
    powerSource_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BatteryInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BatteryInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            batteryStatus_ = rawValue;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            powerSource_ = rawValue;
            break;
          }
          case 29: {

            batteryPercentage_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return google.maps.fleetengine.v1.Vehicles.internal_static_maps_fleetengine_v1_BatteryInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return google.maps.fleetengine.v1.Vehicles.internal_static_maps_fleetengine_v1_BatteryInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            google.maps.fleetengine.v1.BatteryInfo.class, google.maps.fleetengine.v1.BatteryInfo.Builder.class);
  }

  public static final int BATTERY_STATUS_FIELD_NUMBER = 1;
  private int batteryStatus_;
  /**
   * <pre>
   * Status of the battery, whether full or charging etc.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.BatteryStatus battery_status = 1;</code>
   * @return The enum numeric value on the wire for batteryStatus.
   */
  @java.lang.Override public int getBatteryStatusValue() {
    return batteryStatus_;
  }
  /**
   * <pre>
   * Status of the battery, whether full or charging etc.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.BatteryStatus battery_status = 1;</code>
   * @return The batteryStatus.
   */
  @java.lang.Override public google.maps.fleetengine.v1.BatteryStatus getBatteryStatus() {
    @SuppressWarnings("deprecation")
    google.maps.fleetengine.v1.BatteryStatus result = google.maps.fleetengine.v1.BatteryStatus.valueOf(batteryStatus_);
    return result == null ? google.maps.fleetengine.v1.BatteryStatus.UNRECOGNIZED : result;
  }

  public static final int POWER_SOURCE_FIELD_NUMBER = 2;
  private int powerSource_;
  /**
   * <pre>
   * Status of battery power source.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.PowerSource power_source = 2;</code>
   * @return The enum numeric value on the wire for powerSource.
   */
  @java.lang.Override public int getPowerSourceValue() {
    return powerSource_;
  }
  /**
   * <pre>
   * Status of battery power source.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.PowerSource power_source = 2;</code>
   * @return The powerSource.
   */
  @java.lang.Override public google.maps.fleetengine.v1.PowerSource getPowerSource() {
    @SuppressWarnings("deprecation")
    google.maps.fleetengine.v1.PowerSource result = google.maps.fleetengine.v1.PowerSource.valueOf(powerSource_);
    return result == null ? google.maps.fleetengine.v1.PowerSource.UNRECOGNIZED : result;
  }

  public static final int BATTERY_PERCENTAGE_FIELD_NUMBER = 3;
  private float batteryPercentage_;
  /**
   * <pre>
   * Current battery percentage [0-100].
   * </pre>
   *
   * <code>float battery_percentage = 3;</code>
   * @return The batteryPercentage.
   */
  @java.lang.Override
  public float getBatteryPercentage() {
    return batteryPercentage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (batteryStatus_ != google.maps.fleetengine.v1.BatteryStatus.UNKNOWN_BATTERY_STATUS.getNumber()) {
      output.writeEnum(1, batteryStatus_);
    }
    if (powerSource_ != google.maps.fleetengine.v1.PowerSource.UNKNOWN_POWER_SOURCE.getNumber()) {
      output.writeEnum(2, powerSource_);
    }
    if (batteryPercentage_ != 0F) {
      output.writeFloat(3, batteryPercentage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (batteryStatus_ != google.maps.fleetengine.v1.BatteryStatus.UNKNOWN_BATTERY_STATUS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, batteryStatus_);
    }
    if (powerSource_ != google.maps.fleetengine.v1.PowerSource.UNKNOWN_POWER_SOURCE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, powerSource_);
    }
    if (batteryPercentage_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, batteryPercentage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof google.maps.fleetengine.v1.BatteryInfo)) {
      return super.equals(obj);
    }
    google.maps.fleetengine.v1.BatteryInfo other = (google.maps.fleetengine.v1.BatteryInfo) obj;

    if (batteryStatus_ != other.batteryStatus_) return false;
    if (powerSource_ != other.powerSource_) return false;
    if (java.lang.Float.floatToIntBits(getBatteryPercentage())
        != java.lang.Float.floatToIntBits(
            other.getBatteryPercentage())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BATTERY_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + batteryStatus_;
    hash = (37 * hash) + POWER_SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + powerSource_;
    hash = (37 * hash) + BATTERY_PERCENTAGE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getBatteryPercentage());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static google.maps.fleetengine.v1.BatteryInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.BatteryInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.BatteryInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.BatteryInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.BatteryInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.BatteryInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.BatteryInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.BatteryInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.BatteryInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.BatteryInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.BatteryInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.BatteryInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(google.maps.fleetengine.v1.BatteryInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Information about the device's battery.
   * </pre>
   *
   * Protobuf type {@code maps.fleetengine.v1.BatteryInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:maps.fleetengine.v1.BatteryInfo)
      google.maps.fleetengine.v1.BatteryInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.maps.fleetengine.v1.Vehicles.internal_static_maps_fleetengine_v1_BatteryInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.maps.fleetengine.v1.Vehicles.internal_static_maps_fleetengine_v1_BatteryInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.maps.fleetengine.v1.BatteryInfo.class, google.maps.fleetengine.v1.BatteryInfo.Builder.class);
    }

    // Construct using google.maps.fleetengine.v1.BatteryInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      batteryStatus_ = 0;

      powerSource_ = 0;

      batteryPercentage_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return google.maps.fleetengine.v1.Vehicles.internal_static_maps_fleetengine_v1_BatteryInfo_descriptor;
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.BatteryInfo getDefaultInstanceForType() {
      return google.maps.fleetengine.v1.BatteryInfo.getDefaultInstance();
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.BatteryInfo build() {
      google.maps.fleetengine.v1.BatteryInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.BatteryInfo buildPartial() {
      google.maps.fleetengine.v1.BatteryInfo result = new google.maps.fleetengine.v1.BatteryInfo(this);
      result.batteryStatus_ = batteryStatus_;
      result.powerSource_ = powerSource_;
      result.batteryPercentage_ = batteryPercentage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof google.maps.fleetengine.v1.BatteryInfo) {
        return mergeFrom((google.maps.fleetengine.v1.BatteryInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(google.maps.fleetengine.v1.BatteryInfo other) {
      if (other == google.maps.fleetengine.v1.BatteryInfo.getDefaultInstance()) return this;
      if (other.batteryStatus_ != 0) {
        setBatteryStatusValue(other.getBatteryStatusValue());
      }
      if (other.powerSource_ != 0) {
        setPowerSourceValue(other.getPowerSourceValue());
      }
      if (other.getBatteryPercentage() != 0F) {
        setBatteryPercentage(other.getBatteryPercentage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      google.maps.fleetengine.v1.BatteryInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (google.maps.fleetengine.v1.BatteryInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int batteryStatus_ = 0;
    /**
     * <pre>
     * Status of the battery, whether full or charging etc.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.BatteryStatus battery_status = 1;</code>
     * @return The enum numeric value on the wire for batteryStatus.
     */
    @java.lang.Override public int getBatteryStatusValue() {
      return batteryStatus_;
    }
    /**
     * <pre>
     * Status of the battery, whether full or charging etc.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.BatteryStatus battery_status = 1;</code>
     * @param value The enum numeric value on the wire for batteryStatus to set.
     * @return This builder for chaining.
     */
    public Builder setBatteryStatusValue(int value) {
      
      batteryStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Status of the battery, whether full or charging etc.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.BatteryStatus battery_status = 1;</code>
     * @return The batteryStatus.
     */
    @java.lang.Override
    public google.maps.fleetengine.v1.BatteryStatus getBatteryStatus() {
      @SuppressWarnings("deprecation")
      google.maps.fleetengine.v1.BatteryStatus result = google.maps.fleetengine.v1.BatteryStatus.valueOf(batteryStatus_);
      return result == null ? google.maps.fleetengine.v1.BatteryStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Status of the battery, whether full or charging etc.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.BatteryStatus battery_status = 1;</code>
     * @param value The batteryStatus to set.
     * @return This builder for chaining.
     */
    public Builder setBatteryStatus(google.maps.fleetengine.v1.BatteryStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      batteryStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Status of the battery, whether full or charging etc.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.BatteryStatus battery_status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatteryStatus() {
      
      batteryStatus_ = 0;
      onChanged();
      return this;
    }

    private int powerSource_ = 0;
    /**
     * <pre>
     * Status of battery power source.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.PowerSource power_source = 2;</code>
     * @return The enum numeric value on the wire for powerSource.
     */
    @java.lang.Override public int getPowerSourceValue() {
      return powerSource_;
    }
    /**
     * <pre>
     * Status of battery power source.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.PowerSource power_source = 2;</code>
     * @param value The enum numeric value on the wire for powerSource to set.
     * @return This builder for chaining.
     */
    public Builder setPowerSourceValue(int value) {
      
      powerSource_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Status of battery power source.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.PowerSource power_source = 2;</code>
     * @return The powerSource.
     */
    @java.lang.Override
    public google.maps.fleetengine.v1.PowerSource getPowerSource() {
      @SuppressWarnings("deprecation")
      google.maps.fleetengine.v1.PowerSource result = google.maps.fleetengine.v1.PowerSource.valueOf(powerSource_);
      return result == null ? google.maps.fleetengine.v1.PowerSource.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Status of battery power source.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.PowerSource power_source = 2;</code>
     * @param value The powerSource to set.
     * @return This builder for chaining.
     */
    public Builder setPowerSource(google.maps.fleetengine.v1.PowerSource value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      powerSource_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Status of battery power source.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.PowerSource power_source = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPowerSource() {
      
      powerSource_ = 0;
      onChanged();
      return this;
    }

    private float batteryPercentage_ ;
    /**
     * <pre>
     * Current battery percentage [0-100].
     * </pre>
     *
     * <code>float battery_percentage = 3;</code>
     * @return The batteryPercentage.
     */
    @java.lang.Override
    public float getBatteryPercentage() {
      return batteryPercentage_;
    }
    /**
     * <pre>
     * Current battery percentage [0-100].
     * </pre>
     *
     * <code>float battery_percentage = 3;</code>
     * @param value The batteryPercentage to set.
     * @return This builder for chaining.
     */
    public Builder setBatteryPercentage(float value) {
      
      batteryPercentage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Current battery percentage [0-100].
     * </pre>
     *
     * <code>float battery_percentage = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatteryPercentage() {
      
      batteryPercentage_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:maps.fleetengine.v1.BatteryInfo)
  }

  // @@protoc_insertion_point(class_scope:maps.fleetengine.v1.BatteryInfo)
  private static final google.maps.fleetengine.v1.BatteryInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new google.maps.fleetengine.v1.BatteryInfo();
  }

  public static google.maps.fleetengine.v1.BatteryInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatteryInfo>
      PARSER = new com.google.protobuf.AbstractParser<BatteryInfo>() {
    @java.lang.Override
    public BatteryInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BatteryInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BatteryInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatteryInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public google.maps.fleetengine.v1.BatteryInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

