/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/vehicle_api.proto

package google.maps.fleetengine.v1;

/**
 * <pre>
 * CreateVehicle request message.
 * </pre>
 *
 * Protobuf type {@code maps.fleetengine.v1.CreateVehicleRequest}
 */
public final class CreateVehicleRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:maps.fleetengine.v1.CreateVehicleRequest)
    CreateVehicleRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateVehicleRequest.newBuilder() to construct.
  private CreateVehicleRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateVehicleRequest() {
    parent_ = "";
    vehicleId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateVehicleRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateVehicleRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            google.maps.fleetengine.v1.RequestHeader.Builder subBuilder = null;
            if (header_ != null) {
              subBuilder = header_.toBuilder();
            }
            header_ = input.readMessage(google.maps.fleetengine.v1.RequestHeader.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(header_);
              header_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            parent_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            vehicleId_ = s;
            break;
          }
          case 42: {
            google.maps.fleetengine.v1.Vehicle.Builder subBuilder = null;
            if (vehicle_ != null) {
              subBuilder = vehicle_.toBuilder();
            }
            vehicle_ = input.readMessage(google.maps.fleetengine.v1.Vehicle.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(vehicle_);
              vehicle_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return google.maps.fleetengine.v1.VehicleApi.internal_static_maps_fleetengine_v1_CreateVehicleRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return google.maps.fleetengine.v1.VehicleApi.internal_static_maps_fleetengine_v1_CreateVehicleRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            google.maps.fleetengine.v1.CreateVehicleRequest.class, google.maps.fleetengine.v1.CreateVehicleRequest.Builder.class);
  }

  public static final int HEADER_FIELD_NUMBER = 1;
  private google.maps.fleetengine.v1.RequestHeader header_;
  /**
   * <pre>
   * The standard Fleet Engine request header.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
   * @return Whether the header field is set.
   */
  @java.lang.Override
  public boolean hasHeader() {
    return header_ != null;
  }
  /**
   * <pre>
   * The standard Fleet Engine request header.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
   * @return The header.
   */
  @java.lang.Override
  public google.maps.fleetengine.v1.RequestHeader getHeader() {
    return header_ == null ? google.maps.fleetengine.v1.RequestHeader.getDefaultInstance() : header_;
  }
  /**
   * <pre>
   * The standard Fleet Engine request header.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
   */
  @java.lang.Override
  public google.maps.fleetengine.v1.RequestHeaderOrBuilder getHeaderOrBuilder() {
    return getHeader();
  }

  public static final int PARENT_FIELD_NUMBER = 3;
  private volatile java.lang.Object parent_;
  /**
   * <pre>
   * Required. Must be in the format "providers/{provider}".
   * The provider must be the Project ID (for example, sample-cloud-project)
   * of the Google Cloud Project of which the service account making
   * this call is a member.
   * </pre>
   *
   * <code>string parent = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The parent.
   */
  @java.lang.Override
  public java.lang.String getParent() {
    java.lang.Object ref = parent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. Must be in the format "providers/{provider}".
   * The provider must be the Project ID (for example, sample-cloud-project)
   * of the Google Cloud Project of which the service account making
   * this call is a member.
   * </pre>
   *
   * <code>string parent = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for parent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentBytes() {
    java.lang.Object ref = parent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VEHICLE_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object vehicleId_;
  /**
   * <pre>
   * Required. Unique Vehicle ID; must be unique per provider.  The actual
   * format and value is opaque to the Fleet Engine and is determined
   * by the provider.
   * </pre>
   *
   * <code>string vehicle_id = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The vehicleId.
   */
  @java.lang.Override
  public java.lang.String getVehicleId() {
    java.lang.Object ref = vehicleId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vehicleId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. Unique Vehicle ID; must be unique per provider.  The actual
   * format and value is opaque to the Fleet Engine and is determined
   * by the provider.
   * </pre>
   *
   * <code>string vehicle_id = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for vehicleId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVehicleIdBytes() {
    java.lang.Object ref = vehicleId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vehicleId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VEHICLE_FIELD_NUMBER = 5;
  private google.maps.fleetengine.v1.Vehicle vehicle_;
  /**
   * <pre>
   * Required. The Vehicle entity to create. When creating a Vehicle, the following
   * fields are required:
   * * vehicle_state
   * * supported_trip_types
   * * maximum_capacity
   * * vehicle_type
   * When creating a Vehicle, the following fields are ignored:
   * * name
   * * current_trips
   * * available_capacity
   * * current_route_segment
   * * current_route_segment_version
   * * waypoints
   * * waypoints_version
   * * remaining_distance_meters
   * * eta_to_next_waypoint
   * * navigation_status
   * All other fields will be used if provided.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.Vehicle vehicle = 5 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the vehicle field is set.
   */
  @java.lang.Override
  public boolean hasVehicle() {
    return vehicle_ != null;
  }
  /**
   * <pre>
   * Required. The Vehicle entity to create. When creating a Vehicle, the following
   * fields are required:
   * * vehicle_state
   * * supported_trip_types
   * * maximum_capacity
   * * vehicle_type
   * When creating a Vehicle, the following fields are ignored:
   * * name
   * * current_trips
   * * available_capacity
   * * current_route_segment
   * * current_route_segment_version
   * * waypoints
   * * waypoints_version
   * * remaining_distance_meters
   * * eta_to_next_waypoint
   * * navigation_status
   * All other fields will be used if provided.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.Vehicle vehicle = 5 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The vehicle.
   */
  @java.lang.Override
  public google.maps.fleetengine.v1.Vehicle getVehicle() {
    return vehicle_ == null ? google.maps.fleetengine.v1.Vehicle.getDefaultInstance() : vehicle_;
  }
  /**
   * <pre>
   * Required. The Vehicle entity to create. When creating a Vehicle, the following
   * fields are required:
   * * vehicle_state
   * * supported_trip_types
   * * maximum_capacity
   * * vehicle_type
   * When creating a Vehicle, the following fields are ignored:
   * * name
   * * current_trips
   * * available_capacity
   * * current_route_segment
   * * current_route_segment_version
   * * waypoints
   * * waypoints_version
   * * remaining_distance_meters
   * * eta_to_next_waypoint
   * * navigation_status
   * All other fields will be used if provided.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.Vehicle vehicle = 5 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public google.maps.fleetengine.v1.VehicleOrBuilder getVehicleOrBuilder() {
    return getVehicle();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (header_ != null) {
      output.writeMessage(1, getHeader());
    }
    if (!getParentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, parent_);
    }
    if (!getVehicleIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, vehicleId_);
    }
    if (vehicle_ != null) {
      output.writeMessage(5, getVehicle());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (header_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeader());
    }
    if (!getParentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, parent_);
    }
    if (!getVehicleIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, vehicleId_);
    }
    if (vehicle_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getVehicle());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof google.maps.fleetengine.v1.CreateVehicleRequest)) {
      return super.equals(obj);
    }
    google.maps.fleetengine.v1.CreateVehicleRequest other = (google.maps.fleetengine.v1.CreateVehicleRequest) obj;

    if (hasHeader() != other.hasHeader()) return false;
    if (hasHeader()) {
      if (!getHeader()
          .equals(other.getHeader())) return false;
    }
    if (!getParent()
        .equals(other.getParent())) return false;
    if (!getVehicleId()
        .equals(other.getVehicleId())) return false;
    if (hasVehicle() != other.hasVehicle()) return false;
    if (hasVehicle()) {
      if (!getVehicle()
          .equals(other.getVehicle())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    hash = (37 * hash) + PARENT_FIELD_NUMBER;
    hash = (53 * hash) + getParent().hashCode();
    hash = (37 * hash) + VEHICLE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getVehicleId().hashCode();
    if (hasVehicle()) {
      hash = (37 * hash) + VEHICLE_FIELD_NUMBER;
      hash = (53 * hash) + getVehicle().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static google.maps.fleetengine.v1.CreateVehicleRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.CreateVehicleRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.CreateVehicleRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.CreateVehicleRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.CreateVehicleRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.CreateVehicleRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.CreateVehicleRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.CreateVehicleRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.CreateVehicleRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.CreateVehicleRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.CreateVehicleRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.CreateVehicleRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(google.maps.fleetengine.v1.CreateVehicleRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * CreateVehicle request message.
   * </pre>
   *
   * Protobuf type {@code maps.fleetengine.v1.CreateVehicleRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:maps.fleetengine.v1.CreateVehicleRequest)
      google.maps.fleetengine.v1.CreateVehicleRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.maps.fleetengine.v1.VehicleApi.internal_static_maps_fleetengine_v1_CreateVehicleRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.maps.fleetengine.v1.VehicleApi.internal_static_maps_fleetengine_v1_CreateVehicleRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.maps.fleetengine.v1.CreateVehicleRequest.class, google.maps.fleetengine.v1.CreateVehicleRequest.Builder.class);
    }

    // Construct using google.maps.fleetengine.v1.CreateVehicleRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (headerBuilder_ == null) {
        header_ = null;
      } else {
        header_ = null;
        headerBuilder_ = null;
      }
      parent_ = "";

      vehicleId_ = "";

      if (vehicleBuilder_ == null) {
        vehicle_ = null;
      } else {
        vehicle_ = null;
        vehicleBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return google.maps.fleetengine.v1.VehicleApi.internal_static_maps_fleetengine_v1_CreateVehicleRequest_descriptor;
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.CreateVehicleRequest getDefaultInstanceForType() {
      return google.maps.fleetengine.v1.CreateVehicleRequest.getDefaultInstance();
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.CreateVehicleRequest build() {
      google.maps.fleetengine.v1.CreateVehicleRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.CreateVehicleRequest buildPartial() {
      google.maps.fleetengine.v1.CreateVehicleRequest result = new google.maps.fleetengine.v1.CreateVehicleRequest(this);
      if (headerBuilder_ == null) {
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
      result.parent_ = parent_;
      result.vehicleId_ = vehicleId_;
      if (vehicleBuilder_ == null) {
        result.vehicle_ = vehicle_;
      } else {
        result.vehicle_ = vehicleBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof google.maps.fleetengine.v1.CreateVehicleRequest) {
        return mergeFrom((google.maps.fleetengine.v1.CreateVehicleRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(google.maps.fleetengine.v1.CreateVehicleRequest other) {
      if (other == google.maps.fleetengine.v1.CreateVehicleRequest.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (!other.getParent().isEmpty()) {
        parent_ = other.parent_;
        onChanged();
      }
      if (!other.getVehicleId().isEmpty()) {
        vehicleId_ = other.vehicleId_;
        onChanged();
      }
      if (other.hasVehicle()) {
        mergeVehicle(other.getVehicle());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      google.maps.fleetengine.v1.CreateVehicleRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (google.maps.fleetengine.v1.CreateVehicleRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private google.maps.fleetengine.v1.RequestHeader header_;
    private com.google.protobuf.SingleFieldBuilderV3<
        google.maps.fleetengine.v1.RequestHeader, google.maps.fleetengine.v1.RequestHeader.Builder, google.maps.fleetengine.v1.RequestHeaderOrBuilder> headerBuilder_;
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return headerBuilder_ != null || header_ != null;
    }
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     * @return The header.
     */
    public google.maps.fleetengine.v1.RequestHeader getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? google.maps.fleetengine.v1.RequestHeader.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public Builder setHeader(google.maps.fleetengine.v1.RequestHeader value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
        onChanged();
      } else {
        headerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public Builder setHeader(
        google.maps.fleetengine.v1.RequestHeader.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
        onChanged();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public Builder mergeHeader(google.maps.fleetengine.v1.RequestHeader value) {
      if (headerBuilder_ == null) {
        if (header_ != null) {
          header_ =
            google.maps.fleetengine.v1.RequestHeader.newBuilder(header_).mergeFrom(value).buildPartial();
        } else {
          header_ = value;
        }
        onChanged();
      } else {
        headerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = null;
        onChanged();
      } else {
        header_ = null;
        headerBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public google.maps.fleetengine.v1.RequestHeader.Builder getHeaderBuilder() {
      
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public google.maps.fleetengine.v1.RequestHeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            google.maps.fleetengine.v1.RequestHeader.getDefaultInstance() : header_;
      }
    }
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        google.maps.fleetengine.v1.RequestHeader, google.maps.fleetengine.v1.RequestHeader.Builder, google.maps.fleetengine.v1.RequestHeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            google.maps.fleetengine.v1.RequestHeader, google.maps.fleetengine.v1.RequestHeader.Builder, google.maps.fleetengine.v1.RequestHeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private java.lang.Object parent_ = "";
    /**
     * <pre>
     * Required. Must be in the format "providers/{provider}".
     * The provider must be the Project ID (for example, sample-cloud-project)
     * of the Google Cloud Project of which the service account making
     * this call is a member.
     * </pre>
     *
     * <code>string parent = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The parent.
     */
    public java.lang.String getParent() {
      java.lang.Object ref = parent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. Must be in the format "providers/{provider}".
     * The provider must be the Project ID (for example, sample-cloud-project)
     * of the Google Cloud Project of which the service account making
     * this call is a member.
     * </pre>
     *
     * <code>string parent = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for parent.
     */
    public com.google.protobuf.ByteString
        getParentBytes() {
      java.lang.Object ref = parent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. Must be in the format "providers/{provider}".
     * The provider must be the Project ID (for example, sample-cloud-project)
     * of the Google Cloud Project of which the service account making
     * this call is a member.
     * </pre>
     *
     * <code>string parent = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The parent to set.
     * @return This builder for chaining.
     */
    public Builder setParent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      parent_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. Must be in the format "providers/{provider}".
     * The provider must be the Project ID (for example, sample-cloud-project)
     * of the Google Cloud Project of which the service account making
     * this call is a member.
     * </pre>
     *
     * <code>string parent = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearParent() {
      
      parent_ = getDefaultInstance().getParent();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. Must be in the format "providers/{provider}".
     * The provider must be the Project ID (for example, sample-cloud-project)
     * of the Google Cloud Project of which the service account making
     * this call is a member.
     * </pre>
     *
     * <code>string parent = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for parent to set.
     * @return This builder for chaining.
     */
    public Builder setParentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      parent_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object vehicleId_ = "";
    /**
     * <pre>
     * Required. Unique Vehicle ID; must be unique per provider.  The actual
     * format and value is opaque to the Fleet Engine and is determined
     * by the provider.
     * </pre>
     *
     * <code>string vehicle_id = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The vehicleId.
     */
    public java.lang.String getVehicleId() {
      java.lang.Object ref = vehicleId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vehicleId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. Unique Vehicle ID; must be unique per provider.  The actual
     * format and value is opaque to the Fleet Engine and is determined
     * by the provider.
     * </pre>
     *
     * <code>string vehicle_id = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for vehicleId.
     */
    public com.google.protobuf.ByteString
        getVehicleIdBytes() {
      java.lang.Object ref = vehicleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vehicleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. Unique Vehicle ID; must be unique per provider.  The actual
     * format and value is opaque to the Fleet Engine and is determined
     * by the provider.
     * </pre>
     *
     * <code>string vehicle_id = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The vehicleId to set.
     * @return This builder for chaining.
     */
    public Builder setVehicleId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      vehicleId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. Unique Vehicle ID; must be unique per provider.  The actual
     * format and value is opaque to the Fleet Engine and is determined
     * by the provider.
     * </pre>
     *
     * <code>string vehicle_id = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearVehicleId() {
      
      vehicleId_ = getDefaultInstance().getVehicleId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. Unique Vehicle ID; must be unique per provider.  The actual
     * format and value is opaque to the Fleet Engine and is determined
     * by the provider.
     * </pre>
     *
     * <code>string vehicle_id = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for vehicleId to set.
     * @return This builder for chaining.
     */
    public Builder setVehicleIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      vehicleId_ = value;
      onChanged();
      return this;
    }

    private google.maps.fleetengine.v1.Vehicle vehicle_;
    private com.google.protobuf.SingleFieldBuilderV3<
        google.maps.fleetengine.v1.Vehicle, google.maps.fleetengine.v1.Vehicle.Builder, google.maps.fleetengine.v1.VehicleOrBuilder> vehicleBuilder_;
    /**
     * <pre>
     * Required. The Vehicle entity to create. When creating a Vehicle, the following
     * fields are required:
     * * vehicle_state
     * * supported_trip_types
     * * maximum_capacity
     * * vehicle_type
     * When creating a Vehicle, the following fields are ignored:
     * * name
     * * current_trips
     * * available_capacity
     * * current_route_segment
     * * current_route_segment_version
     * * waypoints
     * * waypoints_version
     * * remaining_distance_meters
     * * eta_to_next_waypoint
     * * navigation_status
     * All other fields will be used if provided.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.Vehicle vehicle = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the vehicle field is set.
     */
    public boolean hasVehicle() {
      return vehicleBuilder_ != null || vehicle_ != null;
    }
    /**
     * <pre>
     * Required. The Vehicle entity to create. When creating a Vehicle, the following
     * fields are required:
     * * vehicle_state
     * * supported_trip_types
     * * maximum_capacity
     * * vehicle_type
     * When creating a Vehicle, the following fields are ignored:
     * * name
     * * current_trips
     * * available_capacity
     * * current_route_segment
     * * current_route_segment_version
     * * waypoints
     * * waypoints_version
     * * remaining_distance_meters
     * * eta_to_next_waypoint
     * * navigation_status
     * All other fields will be used if provided.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.Vehicle vehicle = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The vehicle.
     */
    public google.maps.fleetengine.v1.Vehicle getVehicle() {
      if (vehicleBuilder_ == null) {
        return vehicle_ == null ? google.maps.fleetengine.v1.Vehicle.getDefaultInstance() : vehicle_;
      } else {
        return vehicleBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Required. The Vehicle entity to create. When creating a Vehicle, the following
     * fields are required:
     * * vehicle_state
     * * supported_trip_types
     * * maximum_capacity
     * * vehicle_type
     * When creating a Vehicle, the following fields are ignored:
     * * name
     * * current_trips
     * * available_capacity
     * * current_route_segment
     * * current_route_segment_version
     * * waypoints
     * * waypoints_version
     * * remaining_distance_meters
     * * eta_to_next_waypoint
     * * navigation_status
     * All other fields will be used if provided.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.Vehicle vehicle = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setVehicle(google.maps.fleetengine.v1.Vehicle value) {
      if (vehicleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        vehicle_ = value;
        onChanged();
      } else {
        vehicleBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Required. The Vehicle entity to create. When creating a Vehicle, the following
     * fields are required:
     * * vehicle_state
     * * supported_trip_types
     * * maximum_capacity
     * * vehicle_type
     * When creating a Vehicle, the following fields are ignored:
     * * name
     * * current_trips
     * * available_capacity
     * * current_route_segment
     * * current_route_segment_version
     * * waypoints
     * * waypoints_version
     * * remaining_distance_meters
     * * eta_to_next_waypoint
     * * navigation_status
     * All other fields will be used if provided.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.Vehicle vehicle = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setVehicle(
        google.maps.fleetengine.v1.Vehicle.Builder builderForValue) {
      if (vehicleBuilder_ == null) {
        vehicle_ = builderForValue.build();
        onChanged();
      } else {
        vehicleBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Required. The Vehicle entity to create. When creating a Vehicle, the following
     * fields are required:
     * * vehicle_state
     * * supported_trip_types
     * * maximum_capacity
     * * vehicle_type
     * When creating a Vehicle, the following fields are ignored:
     * * name
     * * current_trips
     * * available_capacity
     * * current_route_segment
     * * current_route_segment_version
     * * waypoints
     * * waypoints_version
     * * remaining_distance_meters
     * * eta_to_next_waypoint
     * * navigation_status
     * All other fields will be used if provided.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.Vehicle vehicle = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergeVehicle(google.maps.fleetengine.v1.Vehicle value) {
      if (vehicleBuilder_ == null) {
        if (vehicle_ != null) {
          vehicle_ =
            google.maps.fleetengine.v1.Vehicle.newBuilder(vehicle_).mergeFrom(value).buildPartial();
        } else {
          vehicle_ = value;
        }
        onChanged();
      } else {
        vehicleBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Required. The Vehicle entity to create. When creating a Vehicle, the following
     * fields are required:
     * * vehicle_state
     * * supported_trip_types
     * * maximum_capacity
     * * vehicle_type
     * When creating a Vehicle, the following fields are ignored:
     * * name
     * * current_trips
     * * available_capacity
     * * current_route_segment
     * * current_route_segment_version
     * * waypoints
     * * waypoints_version
     * * remaining_distance_meters
     * * eta_to_next_waypoint
     * * navigation_status
     * All other fields will be used if provided.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.Vehicle vehicle = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearVehicle() {
      if (vehicleBuilder_ == null) {
        vehicle_ = null;
        onChanged();
      } else {
        vehicle_ = null;
        vehicleBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Required. The Vehicle entity to create. When creating a Vehicle, the following
     * fields are required:
     * * vehicle_state
     * * supported_trip_types
     * * maximum_capacity
     * * vehicle_type
     * When creating a Vehicle, the following fields are ignored:
     * * name
     * * current_trips
     * * available_capacity
     * * current_route_segment
     * * current_route_segment_version
     * * waypoints
     * * waypoints_version
     * * remaining_distance_meters
     * * eta_to_next_waypoint
     * * navigation_status
     * All other fields will be used if provided.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.Vehicle vehicle = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public google.maps.fleetengine.v1.Vehicle.Builder getVehicleBuilder() {
      
      onChanged();
      return getVehicleFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Required. The Vehicle entity to create. When creating a Vehicle, the following
     * fields are required:
     * * vehicle_state
     * * supported_trip_types
     * * maximum_capacity
     * * vehicle_type
     * When creating a Vehicle, the following fields are ignored:
     * * name
     * * current_trips
     * * available_capacity
     * * current_route_segment
     * * current_route_segment_version
     * * waypoints
     * * waypoints_version
     * * remaining_distance_meters
     * * eta_to_next_waypoint
     * * navigation_status
     * All other fields will be used if provided.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.Vehicle vehicle = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public google.maps.fleetengine.v1.VehicleOrBuilder getVehicleOrBuilder() {
      if (vehicleBuilder_ != null) {
        return vehicleBuilder_.getMessageOrBuilder();
      } else {
        return vehicle_ == null ?
            google.maps.fleetengine.v1.Vehicle.getDefaultInstance() : vehicle_;
      }
    }
    /**
     * <pre>
     * Required. The Vehicle entity to create. When creating a Vehicle, the following
     * fields are required:
     * * vehicle_state
     * * supported_trip_types
     * * maximum_capacity
     * * vehicle_type
     * When creating a Vehicle, the following fields are ignored:
     * * name
     * * current_trips
     * * available_capacity
     * * current_route_segment
     * * current_route_segment_version
     * * waypoints
     * * waypoints_version
     * * remaining_distance_meters
     * * eta_to_next_waypoint
     * * navigation_status
     * All other fields will be used if provided.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.Vehicle vehicle = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        google.maps.fleetengine.v1.Vehicle, google.maps.fleetengine.v1.Vehicle.Builder, google.maps.fleetengine.v1.VehicleOrBuilder> 
        getVehicleFieldBuilder() {
      if (vehicleBuilder_ == null) {
        vehicleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            google.maps.fleetengine.v1.Vehicle, google.maps.fleetengine.v1.Vehicle.Builder, google.maps.fleetengine.v1.VehicleOrBuilder>(
                getVehicle(),
                getParentForChildren(),
                isClean());
        vehicle_ = null;
      }
      return vehicleBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:maps.fleetengine.v1.CreateVehicleRequest)
  }

  // @@protoc_insertion_point(class_scope:maps.fleetengine.v1.CreateVehicleRequest)
  private static final google.maps.fleetengine.v1.CreateVehicleRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new google.maps.fleetengine.v1.CreateVehicleRequest();
  }

  public static google.maps.fleetengine.v1.CreateVehicleRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateVehicleRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateVehicleRequest>() {
    @java.lang.Override
    public CreateVehicleRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateVehicleRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateVehicleRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateVehicleRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public google.maps.fleetengine.v1.CreateVehicleRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

