/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/trip_api.proto

package google.maps.fleetengine.v1;

/**
 * <pre>
 * ReportBillableTrip request message.
 * </pre>
 *
 * Protobuf type {@code maps.fleetengine.v1.ReportBillableTripRequest}
 */
public final class ReportBillableTripRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:maps.fleetengine.v1.ReportBillableTripRequest)
    ReportBillableTripRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReportBillableTripRequest.newBuilder() to construct.
  private ReportBillableTripRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReportBillableTripRequest() {
    name_ = "";
    countryCode_ = "";
    platform_ = 0;
    relatedIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    solutionType_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReportBillableTripRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReportBillableTripRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 18: {
            String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            countryCode_ = s;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            platform_ = rawValue;
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              relatedIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            relatedIds_.add(s);
            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            solutionType_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        relatedIds_ = relatedIds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return TripApi.internal_static_maps_fleetengine_v1_ReportBillableTripRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return TripApi.internal_static_maps_fleetengine_v1_ReportBillableTripRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ReportBillableTripRequest.class, Builder.class);
  }

  /**
   * <pre>
   * Selector for different solution types of a reported trip.
   * </pre>
   *
   * Protobuf enum {@code maps.fleetengine.v1.ReportBillableTripRequest.SolutionType}
   */
  public enum SolutionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * The default value. For backwards-compatibility, the API will use
     * ON_DEMAND_RIDESHARING_AND_DELIVERIES by default which is the first
     * supported solution type.
     * </pre>
     *
     * <code>SOLUTION_TYPE_UNSPECIFIED = 0;</code>
     */
    SOLUTION_TYPE_UNSPECIFIED(0),
    /**
     * <pre>
     * The solution is an on-demand ridesharing and deliveries trip.
     * </pre>
     *
     * <code>ON_DEMAND_RIDESHARING_AND_DELIVERIES = 1;</code>
     */
    ON_DEMAND_RIDESHARING_AND_DELIVERIES(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * The default value. For backwards-compatibility, the API will use
     * ON_DEMAND_RIDESHARING_AND_DELIVERIES by default which is the first
     * supported solution type.
     * </pre>
     *
     * <code>SOLUTION_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int SOLUTION_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <pre>
     * The solution is an on-demand ridesharing and deliveries trip.
     * </pre>
     *
     * <code>ON_DEMAND_RIDESHARING_AND_DELIVERIES = 1;</code>
     */
    public static final int ON_DEMAND_RIDESHARING_AND_DELIVERIES_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static SolutionType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SolutionType forNumber(int value) {
      switch (value) {
        case 0: return SOLUTION_TYPE_UNSPECIFIED;
        case 1: return ON_DEMAND_RIDESHARING_AND_DELIVERIES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SolutionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SolutionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SolutionType>() {
            public SolutionType findValueByNumber(int number) {
              return SolutionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ReportBillableTripRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final SolutionType[] VALUES = values();

    public static SolutionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SolutionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:maps.fleetengine.v1.ReportBillableTripRequest.SolutionType)
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile Object name_;
  /**
   * <pre>
   * Required. Must be in the format
   * "providers/{provider}/billableTrips/{billable_trip}". The
   * provider must be the Project ID (for example, sample-cloud-project) of the
   * Google Cloud Project of which the service account making this call is a
   * member.
   * </pre>
   *
   * <code>string name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The name.
   */
  @Override
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. Must be in the format
   * "providers/{provider}/billableTrips/{billable_trip}". The
   * provider must be the Project ID (for example, sample-cloud-project) of the
   * Google Cloud Project of which the service account making this call is a
   * member.
   * </pre>
   *
   * <code>string name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for name.
   */
  @Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUNTRY_CODE_FIELD_NUMBER = 3;
  private volatile Object countryCode_;
  /**
   * <pre>
   * Required. Two letter country code of the country where the trip takes place. Price is
   * defined according to country code.
   * </pre>
   *
   * <code>string country_code = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The countryCode.
   */
  @Override
  public String getCountryCode() {
    Object ref = countryCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      countryCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. Two letter country code of the country where the trip takes place. Price is
   * defined according to country code.
   * </pre>
   *
   * <code>string country_code = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for countryCode.
   */
  @Override
  public com.google.protobuf.ByteString
      getCountryCodeBytes() {
    Object ref = countryCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      countryCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLATFORM_FIELD_NUMBER = 5;
  private int platform_;
  /**
   * <pre>
   * The platform upon which the request was issued.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.BillingPlatformIdentifier platform = 5;</code>
   * @return The enum numeric value on the wire for platform.
   */
  @Override public int getPlatformValue() {
    return platform_;
  }
  /**
   * <pre>
   * The platform upon which the request was issued.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.BillingPlatformIdentifier platform = 5;</code>
   * @return The platform.
   */
  @Override public BillingPlatformIdentifier getPlatform() {
    @SuppressWarnings("deprecation")
    BillingPlatformIdentifier result = BillingPlatformIdentifier.valueOf(platform_);
    return result == null ? BillingPlatformIdentifier.UNRECOGNIZED : result;
  }

  public static final int RELATED_IDS_FIELD_NUMBER = 6;
  private com.google.protobuf.LazyStringList relatedIds_;
  /**
   * <pre>
   * The identifiers that are directly related to the trip being reported. These
   * are usually IDs (for example, session IDs) of pre-booking operations done
   * before the trip ID is available. The number of related_ids is
   * limited to 50.
   * </pre>
   *
   * <code>repeated string related_ids = 6;</code>
   * @return A list containing the relatedIds.
   */
  public com.google.protobuf.ProtocolStringList
      getRelatedIdsList() {
    return relatedIds_;
  }
  /**
   * <pre>
   * The identifiers that are directly related to the trip being reported. These
   * are usually IDs (for example, session IDs) of pre-booking operations done
   * before the trip ID is available. The number of related_ids is
   * limited to 50.
   * </pre>
   *
   * <code>repeated string related_ids = 6;</code>
   * @return The count of relatedIds.
   */
  public int getRelatedIdsCount() {
    return relatedIds_.size();
  }
  /**
   * <pre>
   * The identifiers that are directly related to the trip being reported. These
   * are usually IDs (for example, session IDs) of pre-booking operations done
   * before the trip ID is available. The number of related_ids is
   * limited to 50.
   * </pre>
   *
   * <code>repeated string related_ids = 6;</code>
   * @param index The index of the element to return.
   * @return The relatedIds at the given index.
   */
  public String getRelatedIds(int index) {
    return relatedIds_.get(index);
  }
  /**
   * <pre>
   * The identifiers that are directly related to the trip being reported. These
   * are usually IDs (for example, session IDs) of pre-booking operations done
   * before the trip ID is available. The number of related_ids is
   * limited to 50.
   * </pre>
   *
   * <code>repeated string related_ids = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the relatedIds at the given index.
   */
  public com.google.protobuf.ByteString
      getRelatedIdsBytes(int index) {
    return relatedIds_.getByteString(index);
  }

  public static final int SOLUTION_TYPE_FIELD_NUMBER = 7;
  private int solutionType_;
  /**
   * <pre>
   * The type of GMP product solution (for example,
   * ON_DEMAND_RIDESHARING_AND_DELIVERIES) used for the reported trip.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.ReportBillableTripRequest.SolutionType solution_type = 7;</code>
   * @return The enum numeric value on the wire for solutionType.
   */
  @Override public int getSolutionTypeValue() {
    return solutionType_;
  }
  /**
   * <pre>
   * The type of GMP product solution (for example,
   * ON_DEMAND_RIDESHARING_AND_DELIVERIES) used for the reported trip.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.ReportBillableTripRequest.SolutionType solution_type = 7;</code>
   * @return The solutionType.
   */
  @Override public SolutionType getSolutionType() {
    @SuppressWarnings("deprecation")
    SolutionType result = SolutionType.valueOf(solutionType_);
    return result == null ? SolutionType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(countryCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, countryCode_);
    }
    if (platform_ != BillingPlatformIdentifier.BILLING_PLATFORM_IDENTIFIER_UNSPECIFIED.getNumber()) {
      output.writeEnum(5, platform_);
    }
    for (int i = 0; i < relatedIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, relatedIds_.getRaw(i));
    }
    if (solutionType_ != SolutionType.SOLUTION_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(7, solutionType_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(countryCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, countryCode_);
    }
    if (platform_ != BillingPlatformIdentifier.BILLING_PLATFORM_IDENTIFIER_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, platform_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < relatedIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(relatedIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRelatedIdsList().size();
    }
    if (solutionType_ != SolutionType.SOLUTION_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, solutionType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ReportBillableTripRequest)) {
      return super.equals(obj);
    }
    ReportBillableTripRequest other = (ReportBillableTripRequest) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getCountryCode()
        .equals(other.getCountryCode())) return false;
    if (platform_ != other.platform_) return false;
    if (!getRelatedIdsList()
        .equals(other.getRelatedIdsList())) return false;
    if (solutionType_ != other.solutionType_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + COUNTRY_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCountryCode().hashCode();
    hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + platform_;
    if (getRelatedIdsCount() > 0) {
      hash = (37 * hash) + RELATED_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getRelatedIdsList().hashCode();
    }
    hash = (37 * hash) + SOLUTION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + solutionType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ReportBillableTripRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ReportBillableTripRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ReportBillableTripRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ReportBillableTripRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ReportBillableTripRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ReportBillableTripRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ReportBillableTripRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ReportBillableTripRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ReportBillableTripRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ReportBillableTripRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ReportBillableTripRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ReportBillableTripRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ReportBillableTripRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ReportBillableTrip request message.
   * </pre>
   *
   * Protobuf type {@code maps.fleetengine.v1.ReportBillableTripRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:maps.fleetengine.v1.ReportBillableTripRequest)
      ReportBillableTripRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TripApi.internal_static_maps_fleetengine_v1_ReportBillableTripRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TripApi.internal_static_maps_fleetengine_v1_ReportBillableTripRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReportBillableTripRequest.class, Builder.class);
    }

    // Construct using google.maps.fleetengine.v1.ReportBillableTripRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      name_ = "";

      countryCode_ = "";

      platform_ = 0;

      relatedIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      solutionType_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return TripApi.internal_static_maps_fleetengine_v1_ReportBillableTripRequest_descriptor;
    }

    @Override
    public ReportBillableTripRequest getDefaultInstanceForType() {
      return ReportBillableTripRequest.getDefaultInstance();
    }

    @Override
    public ReportBillableTripRequest build() {
      ReportBillableTripRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ReportBillableTripRequest buildPartial() {
      ReportBillableTripRequest result = new ReportBillableTripRequest(this);
      int from_bitField0_ = bitField0_;
      result.name_ = name_;
      result.countryCode_ = countryCode_;
      result.platform_ = platform_;
      if (((bitField0_ & 0x00000001) != 0)) {
        relatedIds_ = relatedIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.relatedIds_ = relatedIds_;
      result.solutionType_ = solutionType_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ReportBillableTripRequest) {
        return mergeFrom((ReportBillableTripRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ReportBillableTripRequest other) {
      if (other == ReportBillableTripRequest.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getCountryCode().isEmpty()) {
        countryCode_ = other.countryCode_;
        onChanged();
      }
      if (other.platform_ != 0) {
        setPlatformValue(other.getPlatformValue());
      }
      if (!other.relatedIds_.isEmpty()) {
        if (relatedIds_.isEmpty()) {
          relatedIds_ = other.relatedIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureRelatedIdsIsMutable();
          relatedIds_.addAll(other.relatedIds_);
        }
        onChanged();
      }
      if (other.solutionType_ != 0) {
        setSolutionTypeValue(other.getSolutionTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ReportBillableTripRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ReportBillableTripRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object name_ = "";
    /**
     * <pre>
     * Required. Must be in the format
     * "providers/{provider}/billableTrips/{billable_trip}". The
     * provider must be the Project ID (for example, sample-cloud-project) of the
     * Google Cloud Project of which the service account making this call is a
     * member.
     * </pre>
     *
     * <code>string name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The name.
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Required. Must be in the format
     * "providers/{provider}/billableTrips/{billable_trip}". The
     * provider must be the Project ID (for example, sample-cloud-project) of the
     * Google Cloud Project of which the service account making this call is a
     * member.
     * </pre>
     *
     * <code>string name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. Must be in the format
     * "providers/{provider}/billableTrips/{billable_trip}". The
     * provider must be the Project ID (for example, sample-cloud-project) of the
     * Google Cloud Project of which the service account making this call is a
     * member.
     * </pre>
     *
     * <code>string name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. Must be in the format
     * "providers/{provider}/billableTrips/{billable_trip}". The
     * provider must be the Project ID (for example, sample-cloud-project) of the
     * Google Cloud Project of which the service account making this call is a
     * member.
     * </pre>
     *
     * <code>string name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. Must be in the format
     * "providers/{provider}/billableTrips/{billable_trip}". The
     * provider must be the Project ID (for example, sample-cloud-project) of the
     * Google Cloud Project of which the service account making this call is a
     * member.
     * </pre>
     *
     * <code>string name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private Object countryCode_ = "";
    /**
     * <pre>
     * Required. Two letter country code of the country where the trip takes place. Price is
     * defined according to country code.
     * </pre>
     *
     * <code>string country_code = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The countryCode.
     */
    public String getCountryCode() {
      Object ref = countryCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        countryCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Required. Two letter country code of the country where the trip takes place. Price is
     * defined according to country code.
     * </pre>
     *
     * <code>string country_code = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for countryCode.
     */
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      Object ref = countryCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        countryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. Two letter country code of the country where the trip takes place. Price is
     * defined according to country code.
     * </pre>
     *
     * <code>string country_code = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The countryCode to set.
     * @return This builder for chaining.
     */
    public Builder setCountryCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      countryCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. Two letter country code of the country where the trip takes place. Price is
     * defined according to country code.
     * </pre>
     *
     * <code>string country_code = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearCountryCode() {
      
      countryCode_ = getDefaultInstance().getCountryCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. Two letter country code of the country where the trip takes place. Price is
     * defined according to country code.
     * </pre>
     *
     * <code>string country_code = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for countryCode to set.
     * @return This builder for chaining.
     */
    public Builder setCountryCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      countryCode_ = value;
      onChanged();
      return this;
    }

    private int platform_ = 0;
    /**
     * <pre>
     * The platform upon which the request was issued.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.BillingPlatformIdentifier platform = 5;</code>
     * @return The enum numeric value on the wire for platform.
     */
    @Override public int getPlatformValue() {
      return platform_;
    }
    /**
     * <pre>
     * The platform upon which the request was issued.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.BillingPlatformIdentifier platform = 5;</code>
     * @param value The enum numeric value on the wire for platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformValue(int value) {
      
      platform_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The platform upon which the request was issued.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.BillingPlatformIdentifier platform = 5;</code>
     * @return The platform.
     */
    @Override
    public BillingPlatformIdentifier getPlatform() {
      @SuppressWarnings("deprecation")
      BillingPlatformIdentifier result = BillingPlatformIdentifier.valueOf(platform_);
      return result == null ? BillingPlatformIdentifier.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The platform upon which the request was issued.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.BillingPlatformIdentifier platform = 5;</code>
     * @param value The platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatform(BillingPlatformIdentifier value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      platform_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The platform upon which the request was issued.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.BillingPlatformIdentifier platform = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatform() {
      
      platform_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList relatedIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureRelatedIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        relatedIds_ = new com.google.protobuf.LazyStringArrayList(relatedIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * The identifiers that are directly related to the trip being reported. These
     * are usually IDs (for example, session IDs) of pre-booking operations done
     * before the trip ID is available. The number of related_ids is
     * limited to 50.
     * </pre>
     *
     * <code>repeated string related_ids = 6;</code>
     * @return A list containing the relatedIds.
     */
    public com.google.protobuf.ProtocolStringList
        getRelatedIdsList() {
      return relatedIds_.getUnmodifiableView();
    }
    /**
     * <pre>
     * The identifiers that are directly related to the trip being reported. These
     * are usually IDs (for example, session IDs) of pre-booking operations done
     * before the trip ID is available. The number of related_ids is
     * limited to 50.
     * </pre>
     *
     * <code>repeated string related_ids = 6;</code>
     * @return The count of relatedIds.
     */
    public int getRelatedIdsCount() {
      return relatedIds_.size();
    }
    /**
     * <pre>
     * The identifiers that are directly related to the trip being reported. These
     * are usually IDs (for example, session IDs) of pre-booking operations done
     * before the trip ID is available. The number of related_ids is
     * limited to 50.
     * </pre>
     *
     * <code>repeated string related_ids = 6;</code>
     * @param index The index of the element to return.
     * @return The relatedIds at the given index.
     */
    public String getRelatedIds(int index) {
      return relatedIds_.get(index);
    }
    /**
     * <pre>
     * The identifiers that are directly related to the trip being reported. These
     * are usually IDs (for example, session IDs) of pre-booking operations done
     * before the trip ID is available. The number of related_ids is
     * limited to 50.
     * </pre>
     *
     * <code>repeated string related_ids = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the relatedIds at the given index.
     */
    public com.google.protobuf.ByteString
        getRelatedIdsBytes(int index) {
      return relatedIds_.getByteString(index);
    }
    /**
     * <pre>
     * The identifiers that are directly related to the trip being reported. These
     * are usually IDs (for example, session IDs) of pre-booking operations done
     * before the trip ID is available. The number of related_ids is
     * limited to 50.
     * </pre>
     *
     * <code>repeated string related_ids = 6;</code>
     * @param index The index to set the value at.
     * @param value The relatedIds to set.
     * @return This builder for chaining.
     */
    public Builder setRelatedIds(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRelatedIdsIsMutable();
      relatedIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The identifiers that are directly related to the trip being reported. These
     * are usually IDs (for example, session IDs) of pre-booking operations done
     * before the trip ID is available. The number of related_ids is
     * limited to 50.
     * </pre>
     *
     * <code>repeated string related_ids = 6;</code>
     * @param value The relatedIds to add.
     * @return This builder for chaining.
     */
    public Builder addRelatedIds(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRelatedIdsIsMutable();
      relatedIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The identifiers that are directly related to the trip being reported. These
     * are usually IDs (for example, session IDs) of pre-booking operations done
     * before the trip ID is available. The number of related_ids is
     * limited to 50.
     * </pre>
     *
     * <code>repeated string related_ids = 6;</code>
     * @param values The relatedIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllRelatedIds(
        Iterable<String> values) {
      ensureRelatedIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, relatedIds_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The identifiers that are directly related to the trip being reported. These
     * are usually IDs (for example, session IDs) of pre-booking operations done
     * before the trip ID is available. The number of related_ids is
     * limited to 50.
     * </pre>
     *
     * <code>repeated string related_ids = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRelatedIds() {
      relatedIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The identifiers that are directly related to the trip being reported. These
     * are usually IDs (for example, session IDs) of pre-booking operations done
     * before the trip ID is available. The number of related_ids is
     * limited to 50.
     * </pre>
     *
     * <code>repeated string related_ids = 6;</code>
     * @param value The bytes of the relatedIds to add.
     * @return This builder for chaining.
     */
    public Builder addRelatedIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureRelatedIdsIsMutable();
      relatedIds_.add(value);
      onChanged();
      return this;
    }

    private int solutionType_ = 0;
    /**
     * <pre>
     * The type of GMP product solution (for example,
     * ON_DEMAND_RIDESHARING_AND_DELIVERIES) used for the reported trip.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.ReportBillableTripRequest.SolutionType solution_type = 7;</code>
     * @return The enum numeric value on the wire for solutionType.
     */
    @Override public int getSolutionTypeValue() {
      return solutionType_;
    }
    /**
     * <pre>
     * The type of GMP product solution (for example,
     * ON_DEMAND_RIDESHARING_AND_DELIVERIES) used for the reported trip.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.ReportBillableTripRequest.SolutionType solution_type = 7;</code>
     * @param value The enum numeric value on the wire for solutionType to set.
     * @return This builder for chaining.
     */
    public Builder setSolutionTypeValue(int value) {
      
      solutionType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The type of GMP product solution (for example,
     * ON_DEMAND_RIDESHARING_AND_DELIVERIES) used for the reported trip.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.ReportBillableTripRequest.SolutionType solution_type = 7;</code>
     * @return The solutionType.
     */
    @Override
    public SolutionType getSolutionType() {
      @SuppressWarnings("deprecation")
      SolutionType result = SolutionType.valueOf(solutionType_);
      return result == null ? SolutionType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The type of GMP product solution (for example,
     * ON_DEMAND_RIDESHARING_AND_DELIVERIES) used for the reported trip.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.ReportBillableTripRequest.SolutionType solution_type = 7;</code>
     * @param value The solutionType to set.
     * @return This builder for chaining.
     */
    public Builder setSolutionType(SolutionType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      solutionType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The type of GMP product solution (for example,
     * ON_DEMAND_RIDESHARING_AND_DELIVERIES) used for the reported trip.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.ReportBillableTripRequest.SolutionType solution_type = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSolutionType() {
      
      solutionType_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:maps.fleetengine.v1.ReportBillableTripRequest)
  }

  // @@protoc_insertion_point(class_scope:maps.fleetengine.v1.ReportBillableTripRequest)
  private static final ReportBillableTripRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ReportBillableTripRequest();
  }

  public static ReportBillableTripRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReportBillableTripRequest>
      PARSER = new com.google.protobuf.AbstractParser<ReportBillableTripRequest>() {
    @Override
    public ReportBillableTripRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReportBillableTripRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReportBillableTripRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ReportBillableTripRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public ReportBillableTripRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

