/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/header.proto

package google.maps.fleetengine.v1;

public interface RequestHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maps.fleetengine.v1.RequestHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The language requested. The external form of Google International
   * Identifiers Initiative (III) LanguageCode objects. If none is specified,
   * return a name in any language, with a preference for English if such a
   * name exists.
   * </pre>
   *
   * <code>string language_code = 1;</code>
   * @return The languageCode.
   */
  java.lang.String getLanguageCode();
  /**
   * <pre>
   * The language requested. The external form of Google International
   * Identifiers Initiative (III) LanguageCode objects. If none is specified,
   * return a name in any language, with a preference for English if such a
   * name exists.
   * </pre>
   *
   * <code>string language_code = 1;</code>
   * @return The bytes for languageCode.
   */
  com.google.protobuf.ByteString
      getLanguageCodeBytes();

  /**
   * <pre>
   * Required. CLDR region code of the region where the request originates.
   * </pre>
   *
   * <code>string region_code = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The regionCode.
   */
  java.lang.String getRegionCode();
  /**
   * <pre>
   * Required. CLDR region code of the region where the request originates.
   * </pre>
   *
   * <code>string region_code = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for regionCode.
   */
  com.google.protobuf.ByteString
      getRegionCodeBytes();

  /**
   * <pre>
   * Version of the calling SDK, if applicable.
   * </pre>
   *
   * <code>string sdk_version = 3;</code>
   * @return The sdkVersion.
   */
  java.lang.String getSdkVersion();
  /**
   * <pre>
   * Version of the calling SDK, if applicable.
   * </pre>
   *
   * <code>string sdk_version = 3;</code>
   * @return The bytes for sdkVersion.
   */
  com.google.protobuf.ByteString
      getSdkVersionBytes();

  /**
   * <pre>
   * Version of the operating system on which the calling SDK is running.
   * </pre>
   *
   * <code>string os_version = 4;</code>
   * @return The osVersion.
   */
  java.lang.String getOsVersion();
  /**
   * <pre>
   * Version of the operating system on which the calling SDK is running.
   * </pre>
   *
   * <code>string os_version = 4;</code>
   * @return The bytes for osVersion.
   */
  com.google.protobuf.ByteString
      getOsVersionBytes();

  /**
   * <pre>
   * Model of the device on which the calling SDK is running.
   * </pre>
   *
   * <code>string device_model = 5;</code>
   * @return The deviceModel.
   */
  java.lang.String getDeviceModel();
  /**
   * <pre>
   * Model of the device on which the calling SDK is running.
   * </pre>
   *
   * <code>string device_model = 5;</code>
   * @return The bytes for deviceModel.
   */
  com.google.protobuf.ByteString
      getDeviceModelBytes();
}
