/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/trip_api.proto

package google.maps.fleetengine.v1;

/**
 * <pre>
 * SearchTrips response message.
 * </pre>
 *
 * Protobuf type {@code maps.fleetengine.v1.SearchTripsResponse}
 */
public final class SearchTripsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:maps.fleetengine.v1.SearchTripsResponse)
    SearchTripsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchTripsResponse.newBuilder() to construct.
  private SearchTripsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchTripsResponse() {
    trips_ = java.util.Collections.emptyList();
    nextPageToken_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new SearchTripsResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SearchTripsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              trips_ = new java.util.ArrayList<Trip>();
              mutable_bitField0_ |= 0x00000001;
            }
            trips_.add(
                input.readMessage(Trip.parser(), extensionRegistry));
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            nextPageToken_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        trips_ = java.util.Collections.unmodifiableList(trips_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return TripApi.internal_static_maps_fleetengine_v1_SearchTripsResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return TripApi.internal_static_maps_fleetengine_v1_SearchTripsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SearchTripsResponse.class, Builder.class);
  }

  public static final int TRIPS_FIELD_NUMBER = 1;
  private java.util.List<Trip> trips_;
  /**
   * <pre>
   * The list of trips for the requested vehicle.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
   */
  @Override
  public java.util.List<Trip> getTripsList() {
    return trips_;
  }
  /**
   * <pre>
   * The list of trips for the requested vehicle.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
   */
  @Override
  public java.util.List<? extends TripOrBuilder>
      getTripsOrBuilderList() {
    return trips_;
  }
  /**
   * <pre>
   * The list of trips for the requested vehicle.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
   */
  @Override
  public int getTripsCount() {
    return trips_.size();
  }
  /**
   * <pre>
   * The list of trips for the requested vehicle.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
   */
  @Override
  public Trip getTrips(int index) {
    return trips_.get(index);
  }
  /**
   * <pre>
   * The list of trips for the requested vehicle.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
   */
  @Override
  public TripOrBuilder getTripsOrBuilder(
      int index) {
    return trips_.get(index);
  }

  public static final int NEXT_PAGE_TOKEN_FIELD_NUMBER = 2;
  private volatile Object nextPageToken_;
  /**
   * <pre>
   * Pass this token in the SearchTripsRequest to continue to
   * list results. If all results have been returned, this field is an empty
   * string or not present in the response.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The nextPageToken.
   */
  @Override
  public String getNextPageToken() {
    Object ref = nextPageToken_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      nextPageToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Pass this token in the SearchTripsRequest to continue to
   * list results. If all results have been returned, this field is an empty
   * string or not present in the response.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The bytes for nextPageToken.
   */
  @Override
  public com.google.protobuf.ByteString
      getNextPageTokenBytes() {
    Object ref = nextPageToken_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      nextPageToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < trips_.size(); i++) {
      output.writeMessage(1, trips_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nextPageToken_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nextPageToken_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < trips_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, trips_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nextPageToken_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nextPageToken_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SearchTripsResponse)) {
      return super.equals(obj);
    }
    SearchTripsResponse other = (SearchTripsResponse) obj;

    if (!getTripsList()
        .equals(other.getTripsList())) return false;
    if (!getNextPageToken()
        .equals(other.getNextPageToken())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTripsCount() > 0) {
      hash = (37 * hash) + TRIPS_FIELD_NUMBER;
      hash = (53 * hash) + getTripsList().hashCode();
    }
    hash = (37 * hash) + NEXT_PAGE_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getNextPageToken().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SearchTripsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SearchTripsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SearchTripsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SearchTripsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SearchTripsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SearchTripsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SearchTripsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SearchTripsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SearchTripsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SearchTripsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SearchTripsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SearchTripsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SearchTripsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * SearchTrips response message.
   * </pre>
   *
   * Protobuf type {@code maps.fleetengine.v1.SearchTripsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:maps.fleetengine.v1.SearchTripsResponse)
      SearchTripsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TripApi.internal_static_maps_fleetengine_v1_SearchTripsResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TripApi.internal_static_maps_fleetengine_v1_SearchTripsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SearchTripsResponse.class, Builder.class);
    }

    // Construct using google.maps.fleetengine.v1.SearchTripsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTripsFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (tripsBuilder_ == null) {
        trips_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        tripsBuilder_.clear();
      }
      nextPageToken_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return TripApi.internal_static_maps_fleetengine_v1_SearchTripsResponse_descriptor;
    }

    @Override
    public SearchTripsResponse getDefaultInstanceForType() {
      return SearchTripsResponse.getDefaultInstance();
    }

    @Override
    public SearchTripsResponse build() {
      SearchTripsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SearchTripsResponse buildPartial() {
      SearchTripsResponse result = new SearchTripsResponse(this);
      int from_bitField0_ = bitField0_;
      if (tripsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          trips_ = java.util.Collections.unmodifiableList(trips_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.trips_ = trips_;
      } else {
        result.trips_ = tripsBuilder_.build();
      }
      result.nextPageToken_ = nextPageToken_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SearchTripsResponse) {
        return mergeFrom((SearchTripsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SearchTripsResponse other) {
      if (other == SearchTripsResponse.getDefaultInstance()) return this;
      if (tripsBuilder_ == null) {
        if (!other.trips_.isEmpty()) {
          if (trips_.isEmpty()) {
            trips_ = other.trips_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTripsIsMutable();
            trips_.addAll(other.trips_);
          }
          onChanged();
        }
      } else {
        if (!other.trips_.isEmpty()) {
          if (tripsBuilder_.isEmpty()) {
            tripsBuilder_.dispose();
            tripsBuilder_ = null;
            trips_ = other.trips_;
            bitField0_ = (bitField0_ & ~0x00000001);
            tripsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTripsFieldBuilder() : null;
          } else {
            tripsBuilder_.addAllMessages(other.trips_);
          }
        }
      }
      if (!other.getNextPageToken().isEmpty()) {
        nextPageToken_ = other.nextPageToken_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SearchTripsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SearchTripsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<Trip> trips_ =
      java.util.Collections.emptyList();
    private void ensureTripsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        trips_ = new java.util.ArrayList<Trip>(trips_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Trip, Trip.Builder, TripOrBuilder> tripsBuilder_;

    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public java.util.List<Trip> getTripsList() {
      if (tripsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(trips_);
      } else {
        return tripsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public int getTripsCount() {
      if (tripsBuilder_ == null) {
        return trips_.size();
      } else {
        return tripsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public Trip getTrips(int index) {
      if (tripsBuilder_ == null) {
        return trips_.get(index);
      } else {
        return tripsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public Builder setTrips(
        int index, Trip value) {
      if (tripsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTripsIsMutable();
        trips_.set(index, value);
        onChanged();
      } else {
        tripsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public Builder setTrips(
        int index, Trip.Builder builderForValue) {
      if (tripsBuilder_ == null) {
        ensureTripsIsMutable();
        trips_.set(index, builderForValue.build());
        onChanged();
      } else {
        tripsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public Builder addTrips(Trip value) {
      if (tripsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTripsIsMutable();
        trips_.add(value);
        onChanged();
      } else {
        tripsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public Builder addTrips(
        int index, Trip value) {
      if (tripsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTripsIsMutable();
        trips_.add(index, value);
        onChanged();
      } else {
        tripsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public Builder addTrips(
        Trip.Builder builderForValue) {
      if (tripsBuilder_ == null) {
        ensureTripsIsMutable();
        trips_.add(builderForValue.build());
        onChanged();
      } else {
        tripsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public Builder addTrips(
        int index, Trip.Builder builderForValue) {
      if (tripsBuilder_ == null) {
        ensureTripsIsMutable();
        trips_.add(index, builderForValue.build());
        onChanged();
      } else {
        tripsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public Builder addAllTrips(
        Iterable<? extends Trip> values) {
      if (tripsBuilder_ == null) {
        ensureTripsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, trips_);
        onChanged();
      } else {
        tripsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public Builder clearTrips() {
      if (tripsBuilder_ == null) {
        trips_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        tripsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public Builder removeTrips(int index) {
      if (tripsBuilder_ == null) {
        ensureTripsIsMutable();
        trips_.remove(index);
        onChanged();
      } else {
        tripsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public Trip.Builder getTripsBuilder(
        int index) {
      return getTripsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public TripOrBuilder getTripsOrBuilder(
        int index) {
      if (tripsBuilder_ == null) {
        return trips_.get(index);  } else {
        return tripsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public java.util.List<? extends TripOrBuilder>
         getTripsOrBuilderList() {
      if (tripsBuilder_ != null) {
        return tripsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(trips_);
      }
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public Trip.Builder addTripsBuilder() {
      return getTripsFieldBuilder().addBuilder(
          Trip.getDefaultInstance());
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public Trip.Builder addTripsBuilder(
        int index) {
      return getTripsFieldBuilder().addBuilder(
          index, Trip.getDefaultInstance());
    }
    /**
     * <pre>
     * The list of trips for the requested vehicle.
     * </pre>
     *
     * <code>repeated .maps.fleetengine.v1.Trip trips = 1;</code>
     */
    public java.util.List<Trip.Builder>
         getTripsBuilderList() {
      return getTripsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Trip, Trip.Builder, TripOrBuilder>
        getTripsFieldBuilder() {
      if (tripsBuilder_ == null) {
        tripsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Trip, Trip.Builder, TripOrBuilder>(
                trips_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        trips_ = null;
      }
      return tripsBuilder_;
    }

    private Object nextPageToken_ = "";
    /**
     * <pre>
     * Pass this token in the SearchTripsRequest to continue to
     * list results. If all results have been returned, this field is an empty
     * string or not present in the response.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     * @return The nextPageToken.
     */
    public String getNextPageToken() {
      Object ref = nextPageToken_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nextPageToken_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Pass this token in the SearchTripsRequest to continue to
     * list results. If all results have been returned, this field is an empty
     * string or not present in the response.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     * @return The bytes for nextPageToken.
     */
    public com.google.protobuf.ByteString
        getNextPageTokenBytes() {
      Object ref = nextPageToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nextPageToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Pass this token in the SearchTripsRequest to continue to
     * list results. If all results have been returned, this field is an empty
     * string or not present in the response.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     * @param value The nextPageToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageToken(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nextPageToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pass this token in the SearchTripsRequest to continue to
     * list results. If all results have been returned, this field is an empty
     * string or not present in the response.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNextPageToken() {
      
      nextPageToken_ = getDefaultInstance().getNextPageToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pass this token in the SearchTripsRequest to continue to
     * list results. If all results have been returned, this field is an empty
     * string or not present in the response.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     * @param value The bytes for nextPageToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nextPageToken_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:maps.fleetengine.v1.SearchTripsResponse)
  }

  // @@protoc_insertion_point(class_scope:maps.fleetengine.v1.SearchTripsResponse)
  private static final SearchTripsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SearchTripsResponse();
  }

  public static SearchTripsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchTripsResponse>
      PARSER = new com.google.protobuf.AbstractParser<SearchTripsResponse>() {
    @Override
    public SearchTripsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SearchTripsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SearchTripsResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SearchTripsResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public SearchTripsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

