/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/trips.proto

package google.maps.fleetengine.v1;

/**
 * <pre>
 * The actual location where a stop (pickup/dropoff) happened.
 * </pre>
 *
 * Protobuf type {@code maps.fleetengine.v1.StopLocation}
 */
public final class StopLocation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:maps.fleetengine.v1.StopLocation)
    StopLocationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StopLocation.newBuilder() to construct.
  private StopLocation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StopLocation() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StopLocation();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StopLocation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.type.LatLng.Builder subBuilder = null;
            if (point_ != null) {
              subBuilder = point_.toBuilder();
            }
            point_ = input.readMessage(com.google.type.LatLng.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(point_);
              point_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timestamp_ != null) {
              subBuilder = timestamp_.toBuilder();
            }
            timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestamp_);
              timestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (stopTime_ != null) {
              subBuilder = stopTime_.toBuilder();
            }
            stopTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(stopTime_);
              stopTime_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return google.maps.fleetengine.v1.Trips.internal_static_maps_fleetengine_v1_StopLocation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return google.maps.fleetengine.v1.Trips.internal_static_maps_fleetengine_v1_StopLocation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            google.maps.fleetengine.v1.StopLocation.class, google.maps.fleetengine.v1.StopLocation.Builder.class);
  }

  public static final int POINT_FIELD_NUMBER = 1;
  private com.google.type.LatLng point_;
  /**
   * <pre>
   * Required. Denotes the actual location.
   * </pre>
   *
   * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the point field is set.
   */
  @java.lang.Override
  public boolean hasPoint() {
    return point_ != null;
  }
  /**
   * <pre>
   * Required. Denotes the actual location.
   * </pre>
   *
   * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The point.
   */
  @java.lang.Override
  public com.google.type.LatLng getPoint() {
    return point_ == null ? com.google.type.LatLng.getDefaultInstance() : point_;
  }
  /**
   * <pre>
   * Required. Denotes the actual location.
   * </pre>
   *
   * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public com.google.type.LatLngOrBuilder getPointOrBuilder() {
    return getPoint();
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <pre>
   * The timestamp when the location was measured.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 2;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <pre>
   * The timestamp when the location was measured.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 2;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <pre>
   * The timestamp when the location was measured.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  public static final int STOP_TIME_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp stopTime_;
  /**
   * <pre>
   * Indicates when the stop actually happened.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp stop_time = 3;</code>
   * @return Whether the stopTime field is set.
   */
  @java.lang.Override
  public boolean hasStopTime() {
    return stopTime_ != null;
  }
  /**
   * <pre>
   * Indicates when the stop actually happened.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp stop_time = 3;</code>
   * @return The stopTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getStopTime() {
    return stopTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : stopTime_;
  }
  /**
   * <pre>
   * Indicates when the stop actually happened.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp stop_time = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getStopTimeOrBuilder() {
    return getStopTime();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (point_ != null) {
      output.writeMessage(1, getPoint());
    }
    if (timestamp_ != null) {
      output.writeMessage(2, getTimestamp());
    }
    if (stopTime_ != null) {
      output.writeMessage(3, getStopTime());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (point_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPoint());
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTimestamp());
    }
    if (stopTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getStopTime());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof google.maps.fleetengine.v1.StopLocation)) {
      return super.equals(obj);
    }
    google.maps.fleetengine.v1.StopLocation other = (google.maps.fleetengine.v1.StopLocation) obj;

    if (hasPoint() != other.hasPoint()) return false;
    if (hasPoint()) {
      if (!getPoint()
          .equals(other.getPoint())) return false;
    }
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (hasStopTime() != other.hasStopTime()) return false;
    if (hasStopTime()) {
      if (!getStopTime()
          .equals(other.getStopTime())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPoint()) {
      hash = (37 * hash) + POINT_FIELD_NUMBER;
      hash = (53 * hash) + getPoint().hashCode();
    }
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    if (hasStopTime()) {
      hash = (37 * hash) + STOP_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getStopTime().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static google.maps.fleetengine.v1.StopLocation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.StopLocation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.StopLocation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.StopLocation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.StopLocation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.StopLocation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.StopLocation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.StopLocation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.StopLocation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.StopLocation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.StopLocation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.StopLocation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(google.maps.fleetengine.v1.StopLocation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The actual location where a stop (pickup/dropoff) happened.
   * </pre>
   *
   * Protobuf type {@code maps.fleetengine.v1.StopLocation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:maps.fleetengine.v1.StopLocation)
      google.maps.fleetengine.v1.StopLocationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.maps.fleetengine.v1.Trips.internal_static_maps_fleetengine_v1_StopLocation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.maps.fleetengine.v1.Trips.internal_static_maps_fleetengine_v1_StopLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.maps.fleetengine.v1.StopLocation.class, google.maps.fleetengine.v1.StopLocation.Builder.class);
    }

    // Construct using google.maps.fleetengine.v1.StopLocation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (pointBuilder_ == null) {
        point_ = null;
      } else {
        point_ = null;
        pointBuilder_ = null;
      }
      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      if (stopTimeBuilder_ == null) {
        stopTime_ = null;
      } else {
        stopTime_ = null;
        stopTimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return google.maps.fleetengine.v1.Trips.internal_static_maps_fleetengine_v1_StopLocation_descriptor;
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.StopLocation getDefaultInstanceForType() {
      return google.maps.fleetengine.v1.StopLocation.getDefaultInstance();
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.StopLocation build() {
      google.maps.fleetengine.v1.StopLocation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.StopLocation buildPartial() {
      google.maps.fleetengine.v1.StopLocation result = new google.maps.fleetengine.v1.StopLocation(this);
      if (pointBuilder_ == null) {
        result.point_ = point_;
      } else {
        result.point_ = pointBuilder_.build();
      }
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      if (stopTimeBuilder_ == null) {
        result.stopTime_ = stopTime_;
      } else {
        result.stopTime_ = stopTimeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof google.maps.fleetengine.v1.StopLocation) {
        return mergeFrom((google.maps.fleetengine.v1.StopLocation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(google.maps.fleetengine.v1.StopLocation other) {
      if (other == google.maps.fleetengine.v1.StopLocation.getDefaultInstance()) return this;
      if (other.hasPoint()) {
        mergePoint(other.getPoint());
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (other.hasStopTime()) {
        mergeStopTime(other.getStopTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      google.maps.fleetengine.v1.StopLocation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (google.maps.fleetengine.v1.StopLocation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.type.LatLng point_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.LatLng, com.google.type.LatLng.Builder, com.google.type.LatLngOrBuilder> pointBuilder_;
    /**
     * <pre>
     * Required. Denotes the actual location.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the point field is set.
     */
    public boolean hasPoint() {
      return pointBuilder_ != null || point_ != null;
    }
    /**
     * <pre>
     * Required. Denotes the actual location.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The point.
     */
    public com.google.type.LatLng getPoint() {
      if (pointBuilder_ == null) {
        return point_ == null ? com.google.type.LatLng.getDefaultInstance() : point_;
      } else {
        return pointBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Required. Denotes the actual location.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setPoint(com.google.type.LatLng value) {
      if (pointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        point_ = value;
        onChanged();
      } else {
        pointBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Required. Denotes the actual location.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setPoint(
        com.google.type.LatLng.Builder builderForValue) {
      if (pointBuilder_ == null) {
        point_ = builderForValue.build();
        onChanged();
      } else {
        pointBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Required. Denotes the actual location.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergePoint(com.google.type.LatLng value) {
      if (pointBuilder_ == null) {
        if (point_ != null) {
          point_ =
            com.google.type.LatLng.newBuilder(point_).mergeFrom(value).buildPartial();
        } else {
          point_ = value;
        }
        onChanged();
      } else {
        pointBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Required. Denotes the actual location.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearPoint() {
      if (pointBuilder_ == null) {
        point_ = null;
        onChanged();
      } else {
        point_ = null;
        pointBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Required. Denotes the actual location.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.type.LatLng.Builder getPointBuilder() {
      
      onChanged();
      return getPointFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Required. Denotes the actual location.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.type.LatLngOrBuilder getPointOrBuilder() {
      if (pointBuilder_ != null) {
        return pointBuilder_.getMessageOrBuilder();
      } else {
        return point_ == null ?
            com.google.type.LatLng.getDefaultInstance() : point_;
      }
    }
    /**
     * <pre>
     * Required. Denotes the actual location.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.LatLng, com.google.type.LatLng.Builder, com.google.type.LatLngOrBuilder> 
        getPointFieldBuilder() {
      if (pointBuilder_ == null) {
        pointBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.LatLng, com.google.type.LatLng.Builder, com.google.type.LatLngOrBuilder>(
                getPoint(),
                getParentForChildren(),
                isClean());
        point_ = null;
      }
      return pointBuilder_;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <pre>
     * The timestamp when the location was measured.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <pre>
     * The timestamp when the location was measured.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The timestamp when the location was measured.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The timestamp when the location was measured.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The timestamp when the location was measured.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The timestamp when the location was measured.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The timestamp when the location was measured.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The timestamp when the location was measured.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <pre>
     * The timestamp when the location was measured.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private com.google.protobuf.Timestamp stopTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> stopTimeBuilder_;
    /**
     * <pre>
     * Indicates when the stop actually happened.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp stop_time = 3;</code>
     * @return Whether the stopTime field is set.
     */
    public boolean hasStopTime() {
      return stopTimeBuilder_ != null || stopTime_ != null;
    }
    /**
     * <pre>
     * Indicates when the stop actually happened.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp stop_time = 3;</code>
     * @return The stopTime.
     */
    public com.google.protobuf.Timestamp getStopTime() {
      if (stopTimeBuilder_ == null) {
        return stopTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : stopTime_;
      } else {
        return stopTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Indicates when the stop actually happened.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp stop_time = 3;</code>
     */
    public Builder setStopTime(com.google.protobuf.Timestamp value) {
      if (stopTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        stopTime_ = value;
        onChanged();
      } else {
        stopTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Indicates when the stop actually happened.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp stop_time = 3;</code>
     */
    public Builder setStopTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (stopTimeBuilder_ == null) {
        stopTime_ = builderForValue.build();
        onChanged();
      } else {
        stopTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Indicates when the stop actually happened.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp stop_time = 3;</code>
     */
    public Builder mergeStopTime(com.google.protobuf.Timestamp value) {
      if (stopTimeBuilder_ == null) {
        if (stopTime_ != null) {
          stopTime_ =
            com.google.protobuf.Timestamp.newBuilder(stopTime_).mergeFrom(value).buildPartial();
        } else {
          stopTime_ = value;
        }
        onChanged();
      } else {
        stopTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Indicates when the stop actually happened.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp stop_time = 3;</code>
     */
    public Builder clearStopTime() {
      if (stopTimeBuilder_ == null) {
        stopTime_ = null;
        onChanged();
      } else {
        stopTime_ = null;
        stopTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Indicates when the stop actually happened.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp stop_time = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getStopTimeBuilder() {
      
      onChanged();
      return getStopTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Indicates when the stop actually happened.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp stop_time = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStopTimeOrBuilder() {
      if (stopTimeBuilder_ != null) {
        return stopTimeBuilder_.getMessageOrBuilder();
      } else {
        return stopTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : stopTime_;
      }
    }
    /**
     * <pre>
     * Indicates when the stop actually happened.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp stop_time = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getStopTimeFieldBuilder() {
      if (stopTimeBuilder_ == null) {
        stopTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getStopTime(),
                getParentForChildren(),
                isClean());
        stopTime_ = null;
      }
      return stopTimeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:maps.fleetengine.v1.StopLocation)
  }

  // @@protoc_insertion_point(class_scope:maps.fleetengine.v1.StopLocation)
  private static final google.maps.fleetengine.v1.StopLocation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new google.maps.fleetengine.v1.StopLocation();
  }

  public static google.maps.fleetengine.v1.StopLocation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StopLocation>
      PARSER = new com.google.protobuf.AbstractParser<StopLocation>() {
    @java.lang.Override
    public StopLocation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StopLocation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StopLocation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StopLocation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public google.maps.fleetengine.v1.StopLocation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

