/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/trips.proto

package google.maps.fleetengine.v1;

public interface StopLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maps.fleetengine.v1.StopLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. Denotes the actual location.
   * </pre>
   *
   * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the point field is set.
   */
  boolean hasPoint();
  /**
   * <pre>
   * Required. Denotes the actual location.
   * </pre>
   *
   * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The point.
   */
  com.google.type.LatLng getPoint();
  /**
   * <pre>
   * Required. Denotes the actual location.
   * </pre>
   *
   * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.type.LatLngOrBuilder getPointOrBuilder();

  /**
   * <pre>
   * The timestamp when the location was measured.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 2;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <pre>
   * The timestamp when the location was measured.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 2;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <pre>
   * The timestamp when the location was measured.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <pre>
   * Indicates when the stop actually happened.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp stop_time = 3;</code>
   * @return Whether the stopTime field is set.
   */
  boolean hasStopTime();
  /**
   * <pre>
   * Indicates when the stop actually happened.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp stop_time = 3;</code>
   * @return The stopTime.
   */
  com.google.protobuf.Timestamp getStopTime();
  /**
   * <pre>
   * Indicates when the stop actually happened.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp stop_time = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStopTimeOrBuilder();
}
