/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/fleetengine.proto

package google.maps.fleetengine.v1;

public interface TerminalPointIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maps.fleetengine.v1.TerminalPointId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string place_id = 2 [deprecated = true];</code>
   * @return Whether the placeId field is set.
   */
  @Deprecated boolean hasPlaceId();
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string place_id = 2 [deprecated = true];</code>
   * @return The placeId.
   */
  @Deprecated String getPlaceId();
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string place_id = 2 [deprecated = true];</code>
   * @return The bytes for placeId.
   */
  @Deprecated com.google.protobuf.ByteString
      getPlaceIdBytes();

  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string generated_id = 3 [deprecated = true];</code>
   * @return Whether the generatedId field is set.
   */
  @Deprecated boolean hasGeneratedId();
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string generated_id = 3 [deprecated = true];</code>
   * @return The generatedId.
   */
  @Deprecated String getGeneratedId();
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string generated_id = 3 [deprecated = true];</code>
   * @return The bytes for generatedId.
   */
  @Deprecated com.google.protobuf.ByteString
      getGeneratedIdBytes();

  /**
   * <pre>
   * Unique ID of the terminal point.
   * </pre>
   *
   * <code>string value = 4;</code>
   * @return The value.
   */
  String getValue();
  /**
   * <pre>
   * Unique ID of the terminal point.
   * </pre>
   *
   * <code>string value = 4;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();

  public TerminalPointId.IdCase getIdCase();
}
