/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/fleetengine.proto

package google.maps.fleetengine.v1;

/**
 * <pre>
 * Describes the location of a pickup or dropoff.
 * </pre>
 *
 * Protobuf type {@code maps.fleetengine.v1.TerminalLocation}
 */
public final class TerminalLocation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:maps.fleetengine.v1.TerminalLocation)
    TerminalLocationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TerminalLocation.newBuilder() to construct.
  private TerminalLocation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TerminalLocation() {
    accessPointId_ = "";
    tripId_ = "";
    terminalLocationType_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TerminalLocation();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TerminalLocation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.type.LatLng.Builder subBuilder = null;
            if (point_ != null) {
              subBuilder = point_.toBuilder();
            }
            point_ = input.readMessage(com.google.type.LatLng.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(point_);
              point_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            TerminalPointId.Builder subBuilder = null;
            if (terminalPointId_ != null) {
              subBuilder = terminalPointId_.toBuilder();
            }
            terminalPointId_ = input.readMessage(TerminalPointId.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(terminalPointId_);
              terminalPointId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            accessPointId_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            tripId_ = s;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            terminalLocationType_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return FleetEngine.internal_static_maps_fleetengine_v1_TerminalLocation_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return FleetEngine.internal_static_maps_fleetengine_v1_TerminalLocation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TerminalLocation.class, Builder.class);
  }

  public static final int POINT_FIELD_NUMBER = 1;
  private com.google.type.LatLng point_;
  /**
   * <pre>
   * Required. Denotes the actual location of a pickup or dropoff.
   * </pre>
   *
   * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the point field is set.
   */
  @Override
  public boolean hasPoint() {
    return point_ != null;
  }
  /**
   * <pre>
   * Required. Denotes the actual location of a pickup or dropoff.
   * </pre>
   *
   * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The point.
   */
  @Override
  public com.google.type.LatLng getPoint() {
    return point_ == null ? com.google.type.LatLng.getDefaultInstance() : point_;
  }
  /**
   * <pre>
   * Required. Denotes the actual location of a pickup or dropoff.
   * </pre>
   *
   * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @Override
  public com.google.type.LatLngOrBuilder getPointOrBuilder() {
    return getPoint();
  }

  public static final int TERMINAL_POINT_ID_FIELD_NUMBER = 2;
  private TerminalPointId terminalPointId_;
  /**
   * <pre>
   * Required. ID of the terminal point.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.TerminalPointId terminal_point_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the terminalPointId field is set.
   */
  @Override
  public boolean hasTerminalPointId() {
    return terminalPointId_ != null;
  }
  /**
   * <pre>
   * Required. ID of the terminal point.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.TerminalPointId terminal_point_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The terminalPointId.
   */
  @Override
  public TerminalPointId getTerminalPointId() {
    return terminalPointId_ == null ? TerminalPointId.getDefaultInstance() : terminalPointId_;
  }
  /**
   * <pre>
   * Required. ID of the terminal point.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.TerminalPointId terminal_point_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @Override
  public TerminalPointIdOrBuilder getTerminalPointIdOrBuilder() {
    return getTerminalPointId();
  }

  public static final int ACCESS_POINT_ID_FIELD_NUMBER = 3;
  private volatile Object accessPointId_;
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string access_point_id = 3 [deprecated = true];</code>
   * @return The accessPointId.
   */
  @Override
  @Deprecated public String getAccessPointId() {
    Object ref = accessPointId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      accessPointId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string access_point_id = 3 [deprecated = true];</code>
   * @return The bytes for accessPointId.
   */
  @Override
  @Deprecated public com.google.protobuf.ByteString
      getAccessPointIdBytes() {
    Object ref = accessPointId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      accessPointId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRIP_ID_FIELD_NUMBER = 4;
  private volatile Object tripId_;
  /**
   * <pre>
   * Deprecated. Use vehicle.waypoint instead.
   * </pre>
   *
   * <code>string trip_id = 4 [deprecated = true];</code>
   * @return The tripId.
   */
  @Override
  @Deprecated public String getTripId() {
    Object ref = tripId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      tripId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Deprecated. Use vehicle.waypoint instead.
   * </pre>
   *
   * <code>string trip_id = 4 [deprecated = true];</code>
   * @return The bytes for tripId.
   */
  @Override
  @Deprecated public com.google.protobuf.ByteString
      getTripIdBytes() {
    Object ref = tripId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      tripId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TERMINAL_LOCATION_TYPE_FIELD_NUMBER = 5;
  private int terminalLocationType_;
  /**
   * <pre>
   * Deprecated. Vehicle.waypoint will have this data.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.WaypointType terminal_location_type = 5 [deprecated = true];</code>
   * @return The enum numeric value on the wire for terminalLocationType.
   */
  @Override @Deprecated public int getTerminalLocationTypeValue() {
    return terminalLocationType_;
  }
  /**
   * <pre>
   * Deprecated. Vehicle.waypoint will have this data.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.WaypointType terminal_location_type = 5 [deprecated = true];</code>
   * @return The terminalLocationType.
   */
  @Override @Deprecated public WaypointType getTerminalLocationType() {
    @SuppressWarnings("deprecation")
    WaypointType result = WaypointType.valueOf(terminalLocationType_);
    return result == null ? WaypointType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (point_ != null) {
      output.writeMessage(1, getPoint());
    }
    if (terminalPointId_ != null) {
      output.writeMessage(2, getTerminalPointId());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accessPointId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, accessPointId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tripId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tripId_);
    }
    if (terminalLocationType_ != WaypointType.UNKNOWN_WAYPOINT_TYPE.getNumber()) {
      output.writeEnum(5, terminalLocationType_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (point_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPoint());
    }
    if (terminalPointId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTerminalPointId());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accessPointId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, accessPointId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tripId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, tripId_);
    }
    if (terminalLocationType_ != WaypointType.UNKNOWN_WAYPOINT_TYPE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, terminalLocationType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TerminalLocation)) {
      return super.equals(obj);
    }
    TerminalLocation other = (TerminalLocation) obj;

    if (hasPoint() != other.hasPoint()) return false;
    if (hasPoint()) {
      if (!getPoint()
          .equals(other.getPoint())) return false;
    }
    if (hasTerminalPointId() != other.hasTerminalPointId()) return false;
    if (hasTerminalPointId()) {
      if (!getTerminalPointId()
          .equals(other.getTerminalPointId())) return false;
    }
    if (!getAccessPointId()
        .equals(other.getAccessPointId())) return false;
    if (!getTripId()
        .equals(other.getTripId())) return false;
    if (terminalLocationType_ != other.terminalLocationType_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPoint()) {
      hash = (37 * hash) + POINT_FIELD_NUMBER;
      hash = (53 * hash) + getPoint().hashCode();
    }
    if (hasTerminalPointId()) {
      hash = (37 * hash) + TERMINAL_POINT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTerminalPointId().hashCode();
    }
    hash = (37 * hash) + ACCESS_POINT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAccessPointId().hashCode();
    hash = (37 * hash) + TRIP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTripId().hashCode();
    hash = (37 * hash) + TERMINAL_LOCATION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + terminalLocationType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TerminalLocation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TerminalLocation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TerminalLocation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TerminalLocation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TerminalLocation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TerminalLocation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TerminalLocation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TerminalLocation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TerminalLocation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TerminalLocation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TerminalLocation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TerminalLocation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TerminalLocation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Describes the location of a pickup or dropoff.
   * </pre>
   *
   * Protobuf type {@code maps.fleetengine.v1.TerminalLocation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:maps.fleetengine.v1.TerminalLocation)
      TerminalLocationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FleetEngine.internal_static_maps_fleetengine_v1_TerminalLocation_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FleetEngine.internal_static_maps_fleetengine_v1_TerminalLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TerminalLocation.class, Builder.class);
    }

    // Construct using google.maps.fleetengine.v1.TerminalLocation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (pointBuilder_ == null) {
        point_ = null;
      } else {
        point_ = null;
        pointBuilder_ = null;
      }
      if (terminalPointIdBuilder_ == null) {
        terminalPointId_ = null;
      } else {
        terminalPointId_ = null;
        terminalPointIdBuilder_ = null;
      }
      accessPointId_ = "";

      tripId_ = "";

      terminalLocationType_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return FleetEngine.internal_static_maps_fleetengine_v1_TerminalLocation_descriptor;
    }

    @Override
    public TerminalLocation getDefaultInstanceForType() {
      return TerminalLocation.getDefaultInstance();
    }

    @Override
    public TerminalLocation build() {
      TerminalLocation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TerminalLocation buildPartial() {
      TerminalLocation result = new TerminalLocation(this);
      if (pointBuilder_ == null) {
        result.point_ = point_;
      } else {
        result.point_ = pointBuilder_.build();
      }
      if (terminalPointIdBuilder_ == null) {
        result.terminalPointId_ = terminalPointId_;
      } else {
        result.terminalPointId_ = terminalPointIdBuilder_.build();
      }
      result.accessPointId_ = accessPointId_;
      result.tripId_ = tripId_;
      result.terminalLocationType_ = terminalLocationType_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TerminalLocation) {
        return mergeFrom((TerminalLocation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TerminalLocation other) {
      if (other == TerminalLocation.getDefaultInstance()) return this;
      if (other.hasPoint()) {
        mergePoint(other.getPoint());
      }
      if (other.hasTerminalPointId()) {
        mergeTerminalPointId(other.getTerminalPointId());
      }
      if (!other.getAccessPointId().isEmpty()) {
        accessPointId_ = other.accessPointId_;
        onChanged();
      }
      if (!other.getTripId().isEmpty()) {
        tripId_ = other.tripId_;
        onChanged();
      }
      if (other.terminalLocationType_ != 0) {
        setTerminalLocationTypeValue(other.getTerminalLocationTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TerminalLocation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TerminalLocation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.type.LatLng point_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.LatLng, com.google.type.LatLng.Builder, com.google.type.LatLngOrBuilder> pointBuilder_;
    /**
     * <pre>
     * Required. Denotes the actual location of a pickup or dropoff.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the point field is set.
     */
    public boolean hasPoint() {
      return pointBuilder_ != null || point_ != null;
    }
    /**
     * <pre>
     * Required. Denotes the actual location of a pickup or dropoff.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The point.
     */
    public com.google.type.LatLng getPoint() {
      if (pointBuilder_ == null) {
        return point_ == null ? com.google.type.LatLng.getDefaultInstance() : point_;
      } else {
        return pointBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Required. Denotes the actual location of a pickup or dropoff.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setPoint(com.google.type.LatLng value) {
      if (pointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        point_ = value;
        onChanged();
      } else {
        pointBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Required. Denotes the actual location of a pickup or dropoff.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setPoint(
        com.google.type.LatLng.Builder builderForValue) {
      if (pointBuilder_ == null) {
        point_ = builderForValue.build();
        onChanged();
      } else {
        pointBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Required. Denotes the actual location of a pickup or dropoff.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergePoint(com.google.type.LatLng value) {
      if (pointBuilder_ == null) {
        if (point_ != null) {
          point_ =
            com.google.type.LatLng.newBuilder(point_).mergeFrom(value).buildPartial();
        } else {
          point_ = value;
        }
        onChanged();
      } else {
        pointBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Required. Denotes the actual location of a pickup or dropoff.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearPoint() {
      if (pointBuilder_ == null) {
        point_ = null;
        onChanged();
      } else {
        point_ = null;
        pointBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Required. Denotes the actual location of a pickup or dropoff.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.type.LatLng.Builder getPointBuilder() {
      
      onChanged();
      return getPointFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Required. Denotes the actual location of a pickup or dropoff.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.type.LatLngOrBuilder getPointOrBuilder() {
      if (pointBuilder_ != null) {
        return pointBuilder_.getMessageOrBuilder();
      } else {
        return point_ == null ?
            com.google.type.LatLng.getDefaultInstance() : point_;
      }
    }
    /**
     * <pre>
     * Required. Denotes the actual location of a pickup or dropoff.
     * </pre>
     *
     * <code>.google.type.LatLng point = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.LatLng, com.google.type.LatLng.Builder, com.google.type.LatLngOrBuilder> 
        getPointFieldBuilder() {
      if (pointBuilder_ == null) {
        pointBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.LatLng, com.google.type.LatLng.Builder, com.google.type.LatLngOrBuilder>(
                getPoint(),
                getParentForChildren(),
                isClean());
        point_ = null;
      }
      return pointBuilder_;
    }

    private TerminalPointId terminalPointId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        TerminalPointId, TerminalPointId.Builder, TerminalPointIdOrBuilder> terminalPointIdBuilder_;
    /**
     * <pre>
     * Required. ID of the terminal point.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TerminalPointId terminal_point_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the terminalPointId field is set.
     */
    public boolean hasTerminalPointId() {
      return terminalPointIdBuilder_ != null || terminalPointId_ != null;
    }
    /**
     * <pre>
     * Required. ID of the terminal point.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TerminalPointId terminal_point_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The terminalPointId.
     */
    public TerminalPointId getTerminalPointId() {
      if (terminalPointIdBuilder_ == null) {
        return terminalPointId_ == null ? TerminalPointId.getDefaultInstance() : terminalPointId_;
      } else {
        return terminalPointIdBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Required. ID of the terminal point.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TerminalPointId terminal_point_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setTerminalPointId(TerminalPointId value) {
      if (terminalPointIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        terminalPointId_ = value;
        onChanged();
      } else {
        terminalPointIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Required. ID of the terminal point.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TerminalPointId terminal_point_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setTerminalPointId(
        TerminalPointId.Builder builderForValue) {
      if (terminalPointIdBuilder_ == null) {
        terminalPointId_ = builderForValue.build();
        onChanged();
      } else {
        terminalPointIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Required. ID of the terminal point.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TerminalPointId terminal_point_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergeTerminalPointId(TerminalPointId value) {
      if (terminalPointIdBuilder_ == null) {
        if (terminalPointId_ != null) {
          terminalPointId_ =
            TerminalPointId.newBuilder(terminalPointId_).mergeFrom(value).buildPartial();
        } else {
          terminalPointId_ = value;
        }
        onChanged();
      } else {
        terminalPointIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Required. ID of the terminal point.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TerminalPointId terminal_point_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearTerminalPointId() {
      if (terminalPointIdBuilder_ == null) {
        terminalPointId_ = null;
        onChanged();
      } else {
        terminalPointId_ = null;
        terminalPointIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Required. ID of the terminal point.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TerminalPointId terminal_point_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public TerminalPointId.Builder getTerminalPointIdBuilder() {
      
      onChanged();
      return getTerminalPointIdFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Required. ID of the terminal point.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TerminalPointId terminal_point_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public TerminalPointIdOrBuilder getTerminalPointIdOrBuilder() {
      if (terminalPointIdBuilder_ != null) {
        return terminalPointIdBuilder_.getMessageOrBuilder();
      } else {
        return terminalPointId_ == null ?
            TerminalPointId.getDefaultInstance() : terminalPointId_;
      }
    }
    /**
     * <pre>
     * Required. ID of the terminal point.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TerminalPointId terminal_point_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        TerminalPointId, TerminalPointId.Builder, TerminalPointIdOrBuilder>
        getTerminalPointIdFieldBuilder() {
      if (terminalPointIdBuilder_ == null) {
        terminalPointIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            TerminalPointId, TerminalPointId.Builder, TerminalPointIdOrBuilder>(
                getTerminalPointId(),
                getParentForChildren(),
                isClean());
        terminalPointId_ = null;
      }
      return terminalPointIdBuilder_;
    }

    private Object accessPointId_ = "";
    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string access_point_id = 3 [deprecated = true];</code>
     * @return The accessPointId.
     */
    @Deprecated public String getAccessPointId() {
      Object ref = accessPointId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        accessPointId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string access_point_id = 3 [deprecated = true];</code>
     * @return The bytes for accessPointId.
     */
    @Deprecated public com.google.protobuf.ByteString
        getAccessPointIdBytes() {
      Object ref = accessPointId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        accessPointId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string access_point_id = 3 [deprecated = true];</code>
     * @param value The accessPointId to set.
     * @return This builder for chaining.
     */
    @Deprecated public Builder setAccessPointId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accessPointId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string access_point_id = 3 [deprecated = true];</code>
     * @return This builder for chaining.
     */
    @Deprecated public Builder clearAccessPointId() {
      
      accessPointId_ = getDefaultInstance().getAccessPointId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string access_point_id = 3 [deprecated = true];</code>
     * @param value The bytes for accessPointId to set.
     * @return This builder for chaining.
     */
    @Deprecated public Builder setAccessPointIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accessPointId_ = value;
      onChanged();
      return this;
    }

    private Object tripId_ = "";
    /**
     * <pre>
     * Deprecated. Use vehicle.waypoint instead.
     * </pre>
     *
     * <code>string trip_id = 4 [deprecated = true];</code>
     * @return The tripId.
     */
    @Deprecated public String getTripId() {
      Object ref = tripId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tripId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Deprecated. Use vehicle.waypoint instead.
     * </pre>
     *
     * <code>string trip_id = 4 [deprecated = true];</code>
     * @return The bytes for tripId.
     */
    @Deprecated public com.google.protobuf.ByteString
        getTripIdBytes() {
      Object ref = tripId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tripId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Deprecated. Use vehicle.waypoint instead.
     * </pre>
     *
     * <code>string trip_id = 4 [deprecated = true];</code>
     * @param value The tripId to set.
     * @return This builder for chaining.
     */
    @Deprecated public Builder setTripId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tripId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Deprecated. Use vehicle.waypoint instead.
     * </pre>
     *
     * <code>string trip_id = 4 [deprecated = true];</code>
     * @return This builder for chaining.
     */
    @Deprecated public Builder clearTripId() {
      
      tripId_ = getDefaultInstance().getTripId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Deprecated. Use vehicle.waypoint instead.
     * </pre>
     *
     * <code>string trip_id = 4 [deprecated = true];</code>
     * @param value The bytes for tripId to set.
     * @return This builder for chaining.
     */
    @Deprecated public Builder setTripIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tripId_ = value;
      onChanged();
      return this;
    }

    private int terminalLocationType_ = 0;
    /**
     * <pre>
     * Deprecated. Vehicle.waypoint will have this data.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.WaypointType terminal_location_type = 5 [deprecated = true];</code>
     * @return The enum numeric value on the wire for terminalLocationType.
     */
    @Override @Deprecated public int getTerminalLocationTypeValue() {
      return terminalLocationType_;
    }
    /**
     * <pre>
     * Deprecated. Vehicle.waypoint will have this data.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.WaypointType terminal_location_type = 5 [deprecated = true];</code>
     * @param value The enum numeric value on the wire for terminalLocationType to set.
     * @return This builder for chaining.
     */
    @Deprecated public Builder setTerminalLocationTypeValue(int value) {
      
      terminalLocationType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Deprecated. Vehicle.waypoint will have this data.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.WaypointType terminal_location_type = 5 [deprecated = true];</code>
     * @return The terminalLocationType.
     */
    @Override
    @Deprecated public WaypointType getTerminalLocationType() {
      @SuppressWarnings("deprecation")
      WaypointType result = WaypointType.valueOf(terminalLocationType_);
      return result == null ? WaypointType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Deprecated. Vehicle.waypoint will have this data.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.WaypointType terminal_location_type = 5 [deprecated = true];</code>
     * @param value The terminalLocationType to set.
     * @return This builder for chaining.
     */
    @Deprecated public Builder setTerminalLocationType(WaypointType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      terminalLocationType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Deprecated. Vehicle.waypoint will have this data.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.WaypointType terminal_location_type = 5 [deprecated = true];</code>
     * @return This builder for chaining.
     */
    @Deprecated public Builder clearTerminalLocationType() {
      
      terminalLocationType_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:maps.fleetengine.v1.TerminalLocation)
  }

  // @@protoc_insertion_point(class_scope:maps.fleetengine.v1.TerminalLocation)
  private static final TerminalLocation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TerminalLocation();
  }

  public static TerminalLocation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TerminalLocation>
      PARSER = new com.google.protobuf.AbstractParser<TerminalLocation>() {
    @Override
    public TerminalLocation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TerminalLocation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TerminalLocation> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TerminalLocation> getParserForType() {
    return PARSER;
  }

  @Override
  public TerminalLocation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

