/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/fleetengine.proto

package google.maps.fleetengine.v1;

/**
 * <pre>
 * Identifies a terminal point.
 * </pre>
 *
 * Protobuf type {@code maps.fleetengine.v1.TerminalPointId}
 */
public final class TerminalPointId extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:maps.fleetengine.v1.TerminalPointId)
    TerminalPointIdOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TerminalPointId.newBuilder() to construct.
  private TerminalPointId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TerminalPointId() {
    value_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TerminalPointId();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TerminalPointId(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 18: {
            String s = input.readStringRequireUtf8();
            idCase_ = 2;
            id_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();
            idCase_ = 3;
            id_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            value_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return FleetEngine.internal_static_maps_fleetengine_v1_TerminalPointId_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return FleetEngine.internal_static_maps_fleetengine_v1_TerminalPointId_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TerminalPointId.class, Builder.class);
  }

  private int idCase_ = 0;
  private Object id_;
  public enum IdCase
      implements com.google.protobuf.Internal.EnumLite,
          InternalOneOfEnum {
    @Deprecated PLACE_ID(2),
    @Deprecated GENERATED_ID(3),
    ID_NOT_SET(0);
    private final int value;
    private IdCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static IdCase valueOf(int value) {
      return forNumber(value);
    }

    public static IdCase forNumber(int value) {
      switch (value) {
        case 2: return PLACE_ID;
        case 3: return GENERATED_ID;
        case 0: return ID_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public IdCase
  getIdCase() {
    return IdCase.forNumber(
        idCase_);
  }

  public static final int PLACE_ID_FIELD_NUMBER = 2;
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string place_id = 2 [deprecated = true];</code>
   * @return Whether the placeId field is set.
   */
  @Deprecated public boolean hasPlaceId() {
    return idCase_ == 2;
  }
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string place_id = 2 [deprecated = true];</code>
   * @return The placeId.
   */
  @Deprecated public String getPlaceId() {
    Object ref = "";
    if (idCase_ == 2) {
      ref = id_;
    }
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (idCase_ == 2) {
        id_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string place_id = 2 [deprecated = true];</code>
   * @return The bytes for placeId.
   */
  @Deprecated public com.google.protobuf.ByteString
      getPlaceIdBytes() {
    Object ref = "";
    if (idCase_ == 2) {
      ref = id_;
    }
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      if (idCase_ == 2) {
        id_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENERATED_ID_FIELD_NUMBER = 3;
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string generated_id = 3 [deprecated = true];</code>
   * @return Whether the generatedId field is set.
   */
  @Deprecated public boolean hasGeneratedId() {
    return idCase_ == 3;
  }
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string generated_id = 3 [deprecated = true];</code>
   * @return The generatedId.
   */
  @Deprecated public String getGeneratedId() {
    Object ref = "";
    if (idCase_ == 3) {
      ref = id_;
    }
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (idCase_ == 3) {
        id_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string generated_id = 3 [deprecated = true];</code>
   * @return The bytes for generatedId.
   */
  @Deprecated public com.google.protobuf.ByteString
      getGeneratedIdBytes() {
    Object ref = "";
    if (idCase_ == 3) {
      ref = id_;
    }
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      if (idCase_ == 3) {
        id_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_FIELD_NUMBER = 4;
  private volatile Object value_;
  /**
   * <pre>
   * Unique ID of the terminal point.
   * </pre>
   *
   * <code>string value = 4;</code>
   * @return The value.
   */
  @Override
  public String getValue() {
    Object ref = value_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      value_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique ID of the terminal point.
   * </pre>
   *
   * <code>string value = 4;</code>
   * @return The bytes for value.
   */
  @Override
  public com.google.protobuf.ByteString
      getValueBytes() {
    Object ref = value_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      value_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
    }
    if (idCase_ == 3) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, value_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
    }
    if (idCase_ == 3) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, value_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TerminalPointId)) {
      return super.equals(obj);
    }
    TerminalPointId other = (TerminalPointId) obj;

    if (!getValue()
        .equals(other.getValue())) return false;
    if (!getIdCase().equals(other.getIdCase())) return false;
    switch (idCase_) {
      case 2:
        if (!getPlaceId()
            .equals(other.getPlaceId())) return false;
        break;
      case 3:
        if (!getGeneratedId()
            .equals(other.getGeneratedId())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue().hashCode();
    switch (idCase_) {
      case 2:
        hash = (37 * hash) + PLACE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getPlaceId().hashCode();
        break;
      case 3:
        hash = (37 * hash) + GENERATED_ID_FIELD_NUMBER;
        hash = (53 * hash) + getGeneratedId().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TerminalPointId parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TerminalPointId parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TerminalPointId parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TerminalPointId parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TerminalPointId parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TerminalPointId parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TerminalPointId parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TerminalPointId parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TerminalPointId parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TerminalPointId parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TerminalPointId parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TerminalPointId parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TerminalPointId prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Identifies a terminal point.
   * </pre>
   *
   * Protobuf type {@code maps.fleetengine.v1.TerminalPointId}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:maps.fleetengine.v1.TerminalPointId)
      TerminalPointIdOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FleetEngine.internal_static_maps_fleetengine_v1_TerminalPointId_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FleetEngine.internal_static_maps_fleetengine_v1_TerminalPointId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TerminalPointId.class, Builder.class);
    }

    // Construct using google.maps.fleetengine.v1.TerminalPointId.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      value_ = "";

      idCase_ = 0;
      id_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return FleetEngine.internal_static_maps_fleetengine_v1_TerminalPointId_descriptor;
    }

    @Override
    public TerminalPointId getDefaultInstanceForType() {
      return TerminalPointId.getDefaultInstance();
    }

    @Override
    public TerminalPointId build() {
      TerminalPointId result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TerminalPointId buildPartial() {
      TerminalPointId result = new TerminalPointId(this);
      if (idCase_ == 2) {
        result.id_ = id_;
      }
      if (idCase_ == 3) {
        result.id_ = id_;
      }
      result.value_ = value_;
      result.idCase_ = idCase_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TerminalPointId) {
        return mergeFrom((TerminalPointId)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TerminalPointId other) {
      if (other == TerminalPointId.getDefaultInstance()) return this;
      if (!other.getValue().isEmpty()) {
        value_ = other.value_;
        onChanged();
      }
      switch (other.getIdCase()) {
        case PLACE_ID: {
          idCase_ = 2;
          id_ = other.id_;
          onChanged();
          break;
        }
        case GENERATED_ID: {
          idCase_ = 3;
          id_ = other.id_;
          onChanged();
          break;
        }
        case ID_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TerminalPointId parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TerminalPointId) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int idCase_ = 0;
    private Object id_;
    public IdCase
        getIdCase() {
      return IdCase.forNumber(
          idCase_);
    }

    public Builder clearId() {
      idCase_ = 0;
      id_ = null;
      onChanged();
      return this;
    }


    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string place_id = 2 [deprecated = true];</code>
     * @return Whether the placeId field is set.
     */
    @Override
    @Deprecated public boolean hasPlaceId() {
      return idCase_ == 2;
    }
    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string place_id = 2 [deprecated = true];</code>
     * @return The placeId.
     */
    @Override
    @Deprecated public String getPlaceId() {
      Object ref = "";
      if (idCase_ == 2) {
        ref = id_;
      }
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (idCase_ == 2) {
          id_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string place_id = 2 [deprecated = true];</code>
     * @return The bytes for placeId.
     */
    @Override
    @Deprecated public com.google.protobuf.ByteString
        getPlaceIdBytes() {
      Object ref = "";
      if (idCase_ == 2) {
        ref = id_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (idCase_ == 2) {
          id_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string place_id = 2 [deprecated = true];</code>
     * @param value The placeId to set.
     * @return This builder for chaining.
     */
    @Deprecated public Builder setPlaceId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  idCase_ = 2;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string place_id = 2 [deprecated = true];</code>
     * @return This builder for chaining.
     */
    @Deprecated public Builder clearPlaceId() {
      if (idCase_ == 2) {
        idCase_ = 0;
        id_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string place_id = 2 [deprecated = true];</code>
     * @param value The bytes for placeId to set.
     * @return This builder for chaining.
     */
    @Deprecated public Builder setPlaceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      idCase_ = 2;
      id_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string generated_id = 3 [deprecated = true];</code>
     * @return Whether the generatedId field is set.
     */
    @Override
    @Deprecated public boolean hasGeneratedId() {
      return idCase_ == 3;
    }
    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string generated_id = 3 [deprecated = true];</code>
     * @return The generatedId.
     */
    @Override
    @Deprecated public String getGeneratedId() {
      Object ref = "";
      if (idCase_ == 3) {
        ref = id_;
      }
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (idCase_ == 3) {
          id_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string generated_id = 3 [deprecated = true];</code>
     * @return The bytes for generatedId.
     */
    @Override
    @Deprecated public com.google.protobuf.ByteString
        getGeneratedIdBytes() {
      Object ref = "";
      if (idCase_ == 3) {
        ref = id_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (idCase_ == 3) {
          id_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string generated_id = 3 [deprecated = true];</code>
     * @param value The generatedId to set.
     * @return This builder for chaining.
     */
    @Deprecated public Builder setGeneratedId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  idCase_ = 3;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string generated_id = 3 [deprecated = true];</code>
     * @return This builder for chaining.
     */
    @Deprecated public Builder clearGeneratedId() {
      if (idCase_ == 3) {
        idCase_ = 0;
        id_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Deprecated.
     * </pre>
     *
     * <code>string generated_id = 3 [deprecated = true];</code>
     * @param value The bytes for generatedId to set.
     * @return This builder for chaining.
     */
    @Deprecated public Builder setGeneratedIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      idCase_ = 3;
      id_ = value;
      onChanged();
      return this;
    }

    private Object value_ = "";
    /**
     * <pre>
     * Unique ID of the terminal point.
     * </pre>
     *
     * <code>string value = 4;</code>
     * @return The value.
     */
    public String getValue() {
      Object ref = value_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        value_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Unique ID of the terminal point.
     * </pre>
     *
     * <code>string value = 4;</code>
     * @return The bytes for value.
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique ID of the terminal point.
     * </pre>
     *
     * <code>string value = 4;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique ID of the terminal point.
     * </pre>
     *
     * <code>string value = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      
      value_ = getDefaultInstance().getValue();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique ID of the terminal point.
     * </pre>
     *
     * <code>string value = 4;</code>
     * @param value The bytes for value to set.
     * @return This builder for chaining.
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      value_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:maps.fleetengine.v1.TerminalPointId)
  }

  // @@protoc_insertion_point(class_scope:maps.fleetengine.v1.TerminalPointId)
  private static final TerminalPointId DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TerminalPointId();
  }

  public static TerminalPointId getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TerminalPointId>
      PARSER = new com.google.protobuf.AbstractParser<TerminalPointId>() {
    @Override
    public TerminalPointId parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TerminalPointId(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TerminalPointId> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TerminalPointId> getParserForType() {
    return PARSER;
  }

  @Override
  public TerminalPointId getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

