/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/vehicle_api.proto

package google.maps.fleetengine.v1;

public interface UpdateVehicleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maps.fleetengine.v1.UpdateVehicleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The standard Fleet Engine request header.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   * The standard Fleet Engine request header.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
   * @return The header.
   */
  google.maps.fleetengine.v1.RequestHeader getHeader();
  /**
   * <pre>
   * The standard Fleet Engine request header.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
   */
  google.maps.fleetengine.v1.RequestHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * Required. Must be in the format
   * "providers/{provider}/vehicles/{vehicle}".
   * The {provider} must be the Project ID (for example, sample-cloud-project)
   * of the Google Cloud Project of which the service account making
   * this call is a member.
   * Note that if the name is also specified in the name field of the
   * vehicle and name is set in the update_mask, both names must be the
   * same.  Otherwise it is an Error.
   * </pre>
   *
   * <code>string name = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Required. Must be in the format
   * "providers/{provider}/vehicles/{vehicle}".
   * The {provider} must be the Project ID (for example, sample-cloud-project)
   * of the Google Cloud Project of which the service account making
   * this call is a member.
   * Note that if the name is also specified in the name field of the
   * vehicle and name is set in the update_mask, both names must be the
   * same.  Otherwise it is an Error.
   * </pre>
   *
   * <code>string name = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Required. The Vehicle entity update to apply.  When updating a Vehicle,
   * the following fields may not be updated as they are managed by the
   * Fleet Engine.
   *   current_trips
   *   available_capacity
   *   current_route_segment_version
   *   waypoints_version
   * Furthermore, the name of the vehicle cannot be updated.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.Vehicle vehicle = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the vehicle field is set.
   */
  boolean hasVehicle();
  /**
   * <pre>
   * Required. The Vehicle entity update to apply.  When updating a Vehicle,
   * the following fields may not be updated as they are managed by the
   * Fleet Engine.
   *   current_trips
   *   available_capacity
   *   current_route_segment_version
   *   waypoints_version
   * Furthermore, the name of the vehicle cannot be updated.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.Vehicle vehicle = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The vehicle.
   */
  google.maps.fleetengine.v1.Vehicle getVehicle();
  /**
   * <pre>
   * Required. The Vehicle entity update to apply.  When updating a Vehicle,
   * the following fields may not be updated as they are managed by the
   * Fleet Engine.
   *   current_trips
   *   available_capacity
   *   current_route_segment_version
   *   waypoints_version
   * Furthermore, the name of the vehicle cannot be updated.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.Vehicle vehicle = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  google.maps.fleetengine.v1.VehicleOrBuilder getVehicleOrBuilder();

  /**
   * <pre>
   * Required. A field mask indicating which fields of the Vehicle to update.
   * The update_mask must contain at least one field.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 5 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the updateMask field is set.
   */
  boolean hasUpdateMask();
  /**
   * <pre>
   * Required. A field mask indicating which fields of the Vehicle to update.
   * The update_mask must contain at least one field.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 5 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The updateMask.
   */
  com.google.protobuf.FieldMask getUpdateMask();
  /**
   * <pre>
   * Required. A field mask indicating which fields of the Vehicle to update.
   * The update_mask must contain at least one field.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 5 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder();
}
